#!/usr/bin/env bash
# 1Panel 计划任务 / crontab：有新提交才构建空闲槽，切流量后停旧槽。
# 强制重建：FORCE=1 bash scripts/deploy-prod.sh
# 只补 3000→当前槽转发（现网 502 时）：bash scripts/deploy-prod.sh edge
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

LOCK="$ROOT/.deploy.lock"
exec 9>"$LOCK"
if ! flock -n 9; then
  echo "[deploy] another deploy is running, skip"
  exit 0
fi

if [[ ! -f .env ]]; then
  echo "[deploy] missing $ROOT/.env" >&2
  exit 1
fi

SLOT_FILE="$ROOT/.deploy-slot"
UPSTREAM_SRC="$ROOT/deploy/openresty/habibi-upstreams.conf"
EDGE_COMPOSE="$ROOT/docker-compose.edge.yml"
DRAIN_SECONDS="${DRAIN_SECONDS:-5}"
UPSTREAM_HOST="${HABIBI_UPSTREAM_HOST:-127.0.0.1}"
MODE="${1:-deploy}"

slot_api_port() {
  case "$1" in
    blue) echo 3001 ;;
    green) echo 3011 ;;
    *) echo "" ;;
  esac
}

slot_web_port() {
  case "$1" in
    blue) echo 3000 ;;
    green) echo 3010 ;;
    *) echo "" ;;
  esac
}

slot_tg_port() {
  case "$1" in
    blue) echo 3002 ;;
    green) echo 3012 ;;
    *) echo "" ;;
  esac
}

slot_admin_port() {
  case "$1" in
    blue) echo 8000 ;;
    green) echo 8010 ;;
    *) echo "" ;;
  esac
}

other_slot() {
  if [[ "$1" == "blue" ]]; then
    echo green
  else
    echo blue
  fi
}

compose() {
  local slot="$1"
  shift
  docker compose \
    -p "habibivpn-${slot}" \
    -f "$ROOT/docker-compose.prod.yml" \
    --env-file "$ROOT/.env" \
    --env-file "$ROOT/deploy/slots/${slot}.env" \
    "$@"
}

url_ok() {
  local code
  code="$(curl -sS -o /dev/null -w '%{http_code}' --max-time 3 "$1" || true)"
  [[ "$code" =~ ^[23] ]]
}

api_ready() {
  url_ok "http://127.0.0.1:$1/health/ready"
}

wait_url() {
  local url="$1"
  local tries="${2:-45}"
  local i
  for i in $(seq 1 "$tries"); do
    if url_ok "$url"; then
      return 0
    fi
    sleep 2
  done
  return 1
}

saved_slot() {
  if [[ -f "$SLOT_FILE" ]]; then
    tr -d '[:space:]' < "$SLOT_FILE"
  fi
}

detect_live_slot() {
  local saved
  saved="$(saved_slot || true)"
  if [[ "$saved" == "blue" || "$saved" == "green" ]]; then
    if api_ready "$(slot_api_port "$saved")"; then
      echo "$saved"
      return
    fi
  fi
  if api_ready 3001; then
    echo blue
    return
  fi
  if api_ready 3011; then
    echo green
    return
  fi
  echo none
}

find_openresty_container() {
  if [[ -n "${OPENRESTY_CONTAINER:-}" ]]; then
    echo "$OPENRESTY_CONTAINER"
    return
  fi
  docker ps --format '{{.Names}}' | grep -iE 'openresty' | head -n 1 || true
}

openresty_conf_dirs() {
  if [[ -n "${OPENRESTY_CONF_DIR:-}" ]]; then
    printf '%s\n' "$OPENRESTY_CONF_DIR"
  fi
  printf '%s\n' \
    /opt/1panel/apps/openresty/openresty/conf/conf.d \
    /opt/1panel/1panel/apps/openresty/openresty/conf/conf.d \
    /opt/1panel/www/conf.d
}

write_upstreams() {
  local slot="$1"
  local web api tg admin
  web="$(slot_web_port "$slot")"
  api="$(slot_api_port "$slot")"
  tg="$(slot_tg_port "$slot")"
  admin="$(slot_admin_port "$slot")"
  mkdir -p "$ROOT/deploy/openresty"
  cat > "$UPSTREAM_SRC" <<EOF
# Generated by scripts/deploy-prod.sh — do not edit by hand.
# active slot: ${slot}

upstream habibi_web {
    server ${UPSTREAM_HOST}:${web};
}

upstream habibi_api {
    server ${UPSTREAM_HOST}:${api};
}

upstream habibi_tg {
    server ${UPSTREAM_HOST}:${tg};
}

upstream habibi_admin {
    server ${UPSTREAM_HOST}:${admin};
}
EOF

  local dir copied=0
  while IFS= read -r dir; do
    [[ -z "$dir" ]] && continue
    if [[ -d "$dir" ]]; then
      cp "$UPSTREAM_SRC" "$dir/00-habibi-upstreams.conf"
      echo "[deploy] wrote $dir/00-habibi-upstreams.conf"
      copied=1
    fi
  done < <(openresty_conf_dirs)

  local c
  c="$(find_openresty_container)"
  if [[ "$copied" -eq 0 && -n "$c" ]]; then
    docker cp "$UPSTREAM_SRC" "$c:/usr/local/openresty/nginx/conf/conf.d/00-habibi-upstreams.conf"
    echo "[deploy] copied upstreams into $c"
    copied=1
  fi

  if [[ "$copied" -eq 0 ]]; then
    echo "[deploy] OpenResty conf.d not found; set OPENRESTY_CONF_DIR or OPENRESTY_CONTAINER" >&2
    return 1
  fi
}

reload_openresty() {
  local c
  c="$(find_openresty_container)"
  if [[ -n "$c" ]]; then
    docker exec "$c" nginx -t
    docker exec "$c" nginx -s reload
    echo "[deploy] reloaded OpenResty container $c"
    return 0
  fi
  if command -v nginx >/dev/null 2>&1; then
    nginx -t
    nginx -s reload
    echo "[deploy] reloaded host nginx"
    return 0
  fi
  echo "[deploy] no OpenResty/nginx to reload" >&2
  return 1
}

stop_edge() {
  docker compose -p habibivpn-edge -f "$EDGE_COMPOSE" down --remove-orphans >/dev/null 2>&1 || true
  docker rm -f habibivpn-edge-edge-1 habibi-edge 2>/dev/null || true
}

start_edge() {
  echo "[deploy] starting edge 3000/3001/3002/8000 -> green"
  docker compose -p habibivpn-edge -f "$EDGE_COMPOSE" up -d
  if ! wait_url "http://127.0.0.1:3000" 15; then
    echo "[deploy] edge :3000 did not become ready" >&2
    docker compose -p habibivpn-edge -f "$EDGE_COMPOSE" logs --tail 40 || true
    return 1
  fi
  echo "[deploy] edge ready"
}

sync_edge() {
  local slot="$1"
  if [[ "$slot" == "green" ]]; then
    start_edge
  else
    stop_edge
  fi
}

stop_slot() {
  local slot="$1"
  echo "[deploy] stopping $slot"
  compose "$slot" down --remove-orphans || true
  if [[ "$slot" == "blue" ]]; then
    docker compose -p habibivpn -f "$ROOT/docker-compose.prod.yml" --env-file "$ROOT/.env" down --remove-orphans || true
    docker rm -f habibivpn-api-1 habibivpn-web-1 habibivpn-tg-1 habibivpn-admin-1 2>/dev/null || true
  fi
}

wait_slot() {
  local slot="$1"
  local api web tg admin
  api="$(slot_api_port "$slot")"
  web="$(slot_web_port "$slot")"
  tg="$(slot_tg_port "$slot")"
  admin="$(slot_admin_port "$slot")"
  echo "[deploy] waiting for $slot API on :$api"
  if ! wait_url "http://127.0.0.1:${api}/health/ready" 45; then
    echo "[deploy] $slot API did not become ready" >&2
    compose "$slot" logs --tail 80 api
    return 1
  fi
  echo "[deploy] waiting for $slot web on :$web"
  if ! wait_url "http://127.0.0.1:${web}" 30; then
    echo "[deploy] $slot web did not become ready" >&2
    compose "$slot" logs --tail 40 web
    return 1
  fi
  wait_url "http://127.0.0.1:${tg}" 15 || true
  wait_url "http://127.0.0.1:${admin}" 15 || true
  echo "[deploy] $slot ready (web :$web api :$api tg :$tg admin :$admin)"
}

if [[ "$MODE" == "edge" ]]; then
  live="$(detect_live_slot)"
  echo "[deploy] live=$live, syncing edge"
  sync_edge "$live"
  exit 0
fi

need_build=0
if [[ "${FORCE:-0}" == "1" ]]; then
  need_build=1
elif [[ ! -d .git ]]; then
  echo "[deploy] not a git checkout, building anyway"
  need_build=1
else
  git fetch --quiet origin
  local_rev="$(git rev-parse HEAD)"
  if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    remote_rev="$(git rev-parse '@{u}')"
  else
    branch="$(git rev-parse --abbrev-ref HEAD)"
    remote_rev="$(git rev-parse "origin/${branch}")"
  fi
  if [[ "$local_rev" != "$remote_rev" ]]; then
    echo "[deploy] ${local_rev:0:8} -> ${remote_rev:0:8}"
    git pull --ff-only
    need_build=1
  fi
fi

if [[ "$need_build" -eq 0 ]]; then
  echo "[deploy] already up to date"
  exit 0
fi

live="$(detect_live_slot)"
if [[ "$live" == "none" ]]; then
  target=blue
  echo "[deploy] no live slot, starting blue"
else
  target="$(other_slot "$live")"
  echo "[deploy] live=$live -> target=$target"
fi

if [[ "$target" == "blue" ]]; then
  stop_edge
fi

echo "[deploy] building and starting $target"
if ! compose "$target" up -d --build --remove-orphans; then
  echo "[deploy] $target up failed" >&2
  compose "$target" logs --tail 80 || true
  if [[ "$live" != "none" ]]; then
    echo "[deploy] keeping live slot $live"
    compose "$target" down --remove-orphans || true
    sync_edge "$live" || true
  fi
  exit 1
fi

if ! wait_slot "$target"; then
  if [[ "$live" != "none" ]]; then
    echo "[deploy] new slot unhealthy, keeping $live" >&2
    compose "$target" down --remove-orphans || true
    sync_edge "$live" || true
  fi
  exit 1
fi

write_upstreams "$target" || true
reload_openresty || true

if [[ "$live" == "none" ]]; then
  printf '%s\n' "$target" > "$SLOT_FILE"
  compose "$target" ps
  echo "[deploy] first slot $target is live"
  exit 0
fi

echo "[deploy] draining ${DRAIN_SECONDS}s"
sleep "$DRAIN_SECONDS"
stop_slot "$live"
sync_edge "$target"
printf '%s\n' "$target" > "$SLOT_FILE"
compose "$target" ps
echo "[deploy] switched $live -> $target"
