import type { SiteLocale } from "./locale";
import { site } from "./site";

export function t(locale: SiteLocale) {
  return locale === "en" ? en : zh;
}

const zh = {
  nav: {
    home: "首页",
    plans: "套餐",
    connect: "连接",
    account: "我的",
    footerAria: "页脚链接",
    langAria: "语言",
    zh: "中文",
    en: "English",
  },
  footer: {
    nodes: "节点",
    about: "关于",
    privacy: "隐私",
    terms: "协议",
  },
  help: {
    title: "帮助与支持",
    download: { label: "下载 App", desc: "iOS / Android / Windows / macOS" },
    guide: { label: "使用教程", desc: "注册、领取套餐、导入客户端" },
    support: { label: "联系客服", desc: "账号与订阅问题咨询" },
  },
  doc: {
    account: "返回我的",
    home: "回首页",
  },
  home: {
    brand: site.brand,
    slogan: site.slogan,
    leadIn: "打开连接复制订阅链接，或前往套餐续费与升级。",
    leadOut: "注册领取套餐，复制订阅链接，导入客户端即可使用。",
    ctaConnect: "打开连接",
    ctaPlans: "查看套餐",
    ctaStart: "开始使用",
    ctaLogin: "已有账号",
    stepsTitle: "三步连上快速虚拟网络",
    stepsLead: "从注册到导入客户端，全程不到一分钟。",
    step1Title: "注册账号",
    step1Body: `用邮箱创建 ${site.brand} 账号。`,
    step2Title: "领取套餐",
    step2Body: "免费试用可一键领取，自动开通上游订阅。",
    step3Title: "导入客户端",
    step3Body: "复制订阅链接，粘贴到 Hiddify 等客户端。",
    extraTitle: "为什么选择我们",
    extra1Title: "多地区节点",
    extra1Body: "按地区查看节点池状态，列表和地图都能看清覆盖。",
    extra2Title: "一用户多套餐",
    extra2Body: "每个套餐独立订阅链接，续费或改套餐时链接保持不变。",
    extra3Title: "网页即可管理",
    extra3Body: "正式客户端上线前，也可以先注册、领套餐、复制订阅。",
  },
  about: {
    title: "关于我们",
    lead: `${site.brand} —— 简洁可靠的个人 VPN 服务。`,
    whoTitle: "我们是谁",
    whoBody: `${site.brand} 面向需要稳定跨境访问的用户，提供注册、套餐领取、订阅管理与节点概览等一站式体验。`,
    offerTitle: "我们提供什么",
    offer1: "多地区节点池，可在 App 内查看状态与数量",
    offer2: "一用户多套餐：每个套餐独立订阅链接",
    offer3: "续费 / 改套餐时订阅链接保持不变",
    offer4: "兼容 Hiddify 等主流订阅客户端",
    privacyTitle: "隐私说明",
    privacyBefore: "我们仅在提供服务所必需的范围内处理账号与订阅信息。请勿将订阅链接分享给他人，以免账号被滥用。完整说明见",
    privacyLink: "隐私条款",
    privacyMid: "，使用服务前请同时阅读",
    termsLink: "用户协议",
    privacyAfter: "。",
    moreTitle: "更多",
    moreBefore: "使用问题请查看",
    guideLink: "使用教程",
    moreMid: "，或前往",
    supportLink: "联系客服",
    moreAfter: "。",
  },
  guide: {
    title: "使用教程",
    lead: "从注册到连上网络，按下面三步操作即可。",
    s1Title: "1. 注册账号",
    s1Before: "打开",
    s1Link: "注册页",
    s1After: `，用邮箱创建 ${site.brand} 账号。`,
    s2Title: "2. 领取套餐",
    s2Before: "在",
    s2Link: "套餐",
    s2After: "页领取免费试用，或等待管理员为你开通付费套餐。开通后会生成独立订阅链接。",
    s3Title: "3. 导入客户端",
    s3Li1Before: "打开",
    s3Li1Link: "连接",
    s3Li1After: "，如有多套餐可先切换",
    s3Li2: "点击「复制订阅链接」",
    s3Li3: "打开 Hiddify（或其他订阅客户端）→ 添加订阅 → 粘贴链接",
    s3Li4: "更新节点后选择线路连接",
    faqTitle: "常见问题",
    faq1Q: "续费后链接会变吗？",
    faq1A: "不会。同一套餐槽续费 / 改套餐会保持订阅链接不变。",
    faq2Q: "可以同时持有多个套餐吗？",
    faq2A: "可以。每个套餐对应独立上游顾客与订阅链接，在「连接」页切换查看。",
    faq3Q: "节点在哪里看？",
    faq3A: "底栏「节点」可查看地区与在线状态（列表 / 地图）。",
    faq4Q: "没有 App 能用吗？",
    faq4A: "可以。先网页注册并领取套餐，把订阅链接导入 Hiddify 等通用客户端即可。",
    faq5Q: "订阅链接能分享吗？",
    faq5A: "不要分享。别人使用你的链接会占用流量，也可能导致账号被限制。",
    cta: "去领取套餐",
  },
  download: {
    title: `下载 ${site.brand}`,
    lead: "选择你的设备平台。正式包上线前，可先用网页注册与管理套餐。",
    toast: (label: string) => `${label} 客户端即将上线，可先使用网页版`,
    webBefore: "也可以先",
    register: "网页注册",
    guide: "查看使用教程",
    qrAria: "手机扫码打开",
    qrTitle: "手机扫码打开",
    qrHint: "用手机浏览器扫码下载",
    noteTitle: "安装说明",
    noteIos: "iOS 通过 App Store 安装，打开后登录同一账号即可同步套餐。",
    noteAndroid: "Android 可走 Google Play 或 APK。安装来源不明的包前请确认官方地址。",
    noteDesktop: "Windows / macOS 安装包上线后可在本页下载；此前请用网页 + 通用客户端。",
  },
  support: {
    title: "联系客服",
    lead: "账号、套餐、订阅链接等问题可在这里找到我们。",
    chatTitle: "在线客服",
    chatLink: "打开聊天窗口",
    chatHint: "网页或 App 内可直接对话，通常几分钟内回复。",
    mailTitle: "邮箱",
    mailHint: "一般会在 1–2 个工作日内回复。",
    tgTitle: "Telegram",
    tgLink: "打开客服频道 / 机器人",
    tipsTitle: "反馈时请尽量提供",
    tip1: "注册邮箱",
    tip2: "套餐名称或订阅状态截图",
    tip3: "问题发生时间与客户端名称（如 Hiddify）",
    mailCta: "发送邮件",
    mailSubject: `${site.brand} 客服咨询`,
  },
  nodes: {
    title: "节点",
    lead: "后台节点池概览：按地区查看状态与节点数量。",
    loading: "加载节点池…",
    total: "节点总数",
    regions: "覆盖地区",
    health: "在线占比",
    refresh: "刷新",
    healthTitle: "节点健康度",
    onlineOf: (active: number, total: number) => `${active}/${total} 在线`,
    updated: "更新于",
    poolTitle: "地区节点池",
    viewAria: "切换可视化",
    list: "列表",
    map: "地图",
    online: "在线",
    offline: "离线",
    other: "其他",
    statusActive: "正常",
    statusPartial: "部分可用",
    statusOffline: "离线",
  },
  plans: {
    freeTitle: "限时免费",
    freeLead: "适合先试用，一键开通。",
    freeBadge: "免费领取",
    registerClaim: "注册领取",
    goConnect: "去连接",
  },
  register: {
    title: "注册",
    lead: `用邮箱创建 ${site.brand} 账号，领取套餐后即可导入客户端。`,
  },
  invite: {
    validLead: "好友邀请你加入。下载 App 或网页注册，即可领取套餐。",
    invalidLead: "邀请链接无效，你仍可直接注册开始使用。",
    codeLabel: "邀请码",
    join: `加入 ${site.brand}`,
    register: "去注册",
    login: "已有账号",
    downloadLabel: "下载 App",
    morePlatforms: "Windows / macOS 等全部平台",
    toast: (label: string) => `${label}即将上线，请先网页注册使用`,
    qrAria: "手机扫码打开",
    qrTitle: "手机扫码打开",
    qrHint: "用手机浏览器扫码",
    redirectTitle: "邀请页",
    redirectLead: "正在跳转…",
  },
} as const;

const en = {
  nav: {
    home: "Home",
    plans: "Plans",
    connect: "Connect",
    account: "Account",
    footerAria: "Footer",
    langAria: "Language",
    zh: "中文",
    en: "English",
  },
  footer: {
    nodes: "Nodes",
    about: "About",
    privacy: "Privacy",
    terms: "Terms",
  },
  help: {
    title: "Help & support",
    download: { label: "Download the app", desc: "iOS / Android / Windows / macOS" },
    guide: { label: "Setup guide", desc: "Sign up, claim a plan, import a client" },
    support: { label: "Contact support", desc: "Account and subscription help" },
  },
  doc: {
    account: "Back to account",
    home: "Home",
  },
  home: {
    brand: site.brand,
    slogan: "Connect anytime, browse faster",
    leadIn: "Open Connect to copy your subscription link, or renew and upgrade a plan.",
    leadOut: "Sign up, claim a plan, copy the subscription link, and import it into a client.",
    ctaConnect: "Open Connect",
    ctaPlans: "View plans",
    ctaStart: "Get started",
    ctaLogin: "I have an account",
    stepsTitle: "Connect in three steps",
    stepsLead: "From signup to a working client in under a minute.",
    step1Title: "Create an account",
    step1Body: `Sign up for ${site.brand} with your email.`,
    step2Title: "Claim a plan",
    step2Body: "Free trials can be claimed in one tap and provision a subscription automatically.",
    step3Title: "Import a client",
    step3Body: "Copy the subscription link and paste it into Hiddify or another client.",
    extraTitle: "Why it works",
    extra1Title: "Multi-region nodes",
    extra1Body: "Check pool status by region, in a list or on the map.",
    extra2Title: "Multiple plans per user",
    extra2Body: "Each plan has its own subscription link. Renewals keep the same URL.",
    extra3Title: "Manage in the browser",
    extra3Body: "You can sign up, claim a plan, and copy a subscription before native apps ship.",
  },
  about: {
    title: "About us",
    lead: `${site.brand} — a simple, reliable personal VPN.`,
    whoTitle: "Who we are",
    whoBody: `${site.brand} helps people who need stable cross-border access: signup, plan claims, subscription management, and a node overview in one place.`,
    offerTitle: "What you get",
    offer1: "Regional node pools with status and counts in the app",
    offer2: "Multiple plans per user, each with its own subscription link",
    offer3: "The subscription URL stays the same when you renew or change a plan",
    offer4: "Works with Hiddify and other mainstream subscription clients",
    privacyTitle: "Privacy",
    privacyBefore:
      "We only process account and subscription data needed to run the service. Do not share your subscription link. See the",
    privacyLink: "Privacy Policy",
    privacyMid: " and the",
    termsLink: "Terms of Service",
    privacyAfter: " before you use the product.",
    moreTitle: "More",
    moreBefore: "For setup help, read the",
    guideLink: "guide",
    moreMid: " or",
    supportLink: "contact support",
    moreAfter: ".",
  },
  guide: {
    title: "Setup guide",
    lead: "Follow these three steps to get online.",
    s1Title: "1. Create an account",
    s1Before: "Open the",
    s1Link: "sign-up page",
    s1After: ` and create a ${site.brand} account with your email.`,
    s2Title: "2. Claim a plan",
    s2Before: "On the",
    s2Link: "Plans",
    s2After:
      " page, claim a free trial or wait for an admin to provision a paid plan. Each plan gets its own subscription link.",
    s3Title: "3. Import a client",
    s3Li1Before: "Open",
    s3Li1Link: "Connect",
    s3Li1After: " and switch plans if you have more than one",
    s3Li2: "Tap “Copy subscription link”",
    s3Li3: "Open Hiddify (or another client) → Add subscription → paste the link",
    s3Li4: "Update nodes, then pick a line and connect",
    faqTitle: "FAQ",
    faq1Q: "Does the link change after renewal?",
    faq1A: "No. Renewing or changing the plan in the same slot keeps the subscription URL.",
    faq2Q: "Can I hold more than one plan?",
    faq2A: "Yes. Each plan has its own upstream customer and link. Switch them on Connect.",
    faq3Q: "Where do I see nodes?",
    faq3A: "Open Nodes in the footer to see regions and online status (list or map).",
    faq4Q: "Can I use it without the official app?",
    faq4A: "Yes. Sign up on the web, claim a plan, and import the link into Hiddify or another client.",
    faq5Q: "Can I share my subscription link?",
    faq5A: "No. Other people using your link will consume your traffic and may get the account limited.",
    cta: "Claim a plan",
  },
  download: {
    title: `Download ${site.brand}`,
    lead: "Pick your platform. Until installers ship, you can sign up and manage plans on the web.",
    toast: (label: string) => `${label} is coming soon — use the web app for now`,
    webBefore: "Or",
    register: "sign up on the web",
    guide: "read the setup guide",
    qrAria: "Scan to open on your phone",
    qrTitle: "Scan with your phone",
    qrHint: "Open this page in your mobile browser",
    noteTitle: "Install notes",
    noteIos: "Install from the App Store, then sign in with the same account to sync plans.",
    noteAndroid: "Use Google Play or the official APK. Confirm the URL before installing sideloaded packages.",
    noteDesktop: "Windows / macOS builds will appear here. Until then, use the web app plus a generic client.",
  },
  support: {
    title: "Contact support",
    lead: "Account, plan, and subscription questions land here.",
    chatTitle: "Live chat",
    chatLink: "Open the chat",
    chatHint: "Chat on the web or in the app. Replies usually take a few minutes.",
    mailTitle: "Email",
    mailHint: "We typically reply within 1–2 business days.",
    tgTitle: "Telegram",
    tgLink: "Open the support channel / bot",
    tipsTitle: "Please include",
    tip1: "Your signup email",
    tip2: "Plan name or a screenshot of subscription status",
    tip3: "When it happened and the client name (for example Hiddify)",
    mailCta: "Send email",
    mailSubject: `${site.brand} support`,
  },
  nodes: {
    title: "Nodes",
    lead: "Node pool overview: status and counts by region.",
    loading: "Loading node pools…",
    total: "Total nodes",
    regions: "Regions",
    health: "Online",
    refresh: "Refresh",
    healthTitle: "Pool health",
    onlineOf: (active: number, total: number) => `${active}/${total} online`,
    updated: "Updated",
    poolTitle: "Regional pools",
    viewAria: "View mode",
    list: "List",
    map: "Map",
    online: "online",
    offline: "offline",
    other: "other",
    statusActive: "OK",
    statusPartial: "Partial",
    statusOffline: "Offline",
  },
  plans: {
    freeTitle: "Limited-time free",
    freeLead: "Try first — claim in one tap.",
    freeBadge: "Free claim",
    registerClaim: "Sign up to claim",
    goConnect: "Connect",
  },
  register: {
    title: "Sign up",
    lead: `Create a ${site.brand} account with your email, then claim a plan and import a client.`,
  },
  invite: {
    validLead: "A friend invited you. Download the app or sign up on the web to claim a plan.",
    invalidLead: "This invite link is invalid. You can still sign up and get started.",
    codeLabel: "Invite code",
    join: `Join ${site.brand}`,
    register: "Sign up",
    login: "I have an account",
    downloadLabel: "Download the app",
    morePlatforms: "Windows / macOS and all platforms",
    toast: (label: string) => `${label} is coming soon — sign up on the web first`,
    qrAria: "Scan to open on your phone",
    qrTitle: "Scan with your phone",
    qrHint: "Use your phone browser",
    redirectTitle: "Invite",
    redirectLead: "Redirecting…",
  },
} as const;
