import type { SiteLocale } from "./locale";
import { site } from "./site";

export function t(locale: SiteLocale) {
  return locale === "en" ? en : zh;
}

const zh = {
  nav: {
    home: "首页",
    plans: "套餐",
    download: "下载",
    connect: "连接",
    account: "我的",
    userCenter: "用户中心",
    menuAria: "账户菜单",
    footerAria: "页脚链接",
    langAria: "语言",
    zh: "中文",
    en: "English",
  },
  footer: {
    nodes: "节点",
    about: "关于",
    privacy: "隐私",
    terms: "协议",
  },
  help: {
    title: "帮助与支持",
    download: { label: "下载 App", desc: "iOS / Android / Windows / macOS" },
    guide: { label: "使用教程", desc: "官方 App 一键连接，或导入第三方客户端" },
    support: { label: "联系客服", desc: "账号与订阅问题咨询" },
  },
  doc: {
    account: "返回我的",
    home: "回首页",
  },
  home: {
    brand: site.brand,
    slogan: site.slogan,
    leadIn: [
      "最稳定、高速的科学上网工具",
      `既是VPN 也是机场，满足各种环境下使用。`,
    ],
    leadOut: "注册领取套餐，复制订阅链接，导入客户端即可使用。",
    trialChip: (plan: string) => `限时活动 · 注册即送「${plan}」`,
    trialPlanFallback: "体验套餐",
    ctaConnect: "我的套餐",
    ctaPlans: "查看价格",
    ctaStart: "开始使用",
    ctaStartTrial: "免费注册领取",
    ctaLogin: "已有账号",
    downloadLabel: "下载 App",
    downloadMore: "更多下载",
    scrollHint: "向下浏览",
    stepsTitle: "三步连上快速虚拟网络",
    stepsLead: "从注册到导入客户端，全程不到一分钟。",
    step1Title: "注册账号",
    step1Body: `用邮箱创建 ${site.brand} 账号。`,
    step1BodyTrial: `用邮箱注册 ${site.brand}，完成后自动获赠体验套餐。`,
    step2Title: "领取套餐",
    step2Body: "免费试用可一键领取，自动开通上游订阅。",
    step2TitleTrial: "自动开通体验套餐",
    step2BodyTrial: "完成注册后系统自动赠送体验套餐。",
    step3Title: "开始使用",
    step3Body: "使用官方 App 或第三方订阅软件",
    inviteTabGift: "邀请有奖",
    inviteTabPromo: "邀请返佣",
    inviteTabsAria: "邀请活动",
    inviteKicker: "限时活动",
    inviteTitle: "邀请用户得永久免费会员",
    inviteLead: "每邀请 1 个用户送 1 天，满 15 个用户送永久会员",
    inviteCta: "立即邀请",
    invitePerValue: "+1 天",
    invitePerLabel: "每邀请 1 人",
    inviteGoalValue: "满 15 人",
    inviteGoalLabel: "送永久会员",
    promoKicker: "长期推广",
    promoTitle: "邀请好友付费，永久拿佣金",
    promoLead: "好友充值可持续获得佣金，最高 3 层分成。同一邀请码，活动奖励和返佣都能拿。",
    promoCta: "去推广中心",
    promoPerValue: "最高 3 层",
    promoPerLabel: "多级分佣",
    promoGoalValue: "永久",
    promoGoalLabel: "持续返佣",
    featuresTitle: "产品优势",
    features: [
      {
        title: "银行级安全防护",
        body: "采用 **AES-256 高强度加密**，为您的网络连接和数据传输提供可靠保护。无论浏览网页、使用 AI 服务还是连接公共 Wi-Fi，都能更安心。",
        stats: [{ value: "AES-256", label: "高级加密保护" }],
      },
      {
        title: "高速连接，畅快无阻",
        body: "优化全球网络线路，兼顾速度与稳定性。高清视频、AI 服务、网页浏览及大文件传输，都能保持流畅体验。",
        stats: [
          { value: "300 Mbps+", label: "高速下载" },
          { value: "12 ms", label: "低延迟连接" },
        ],
      },
      {
        title: "全球高速节点",
        body: "覆盖全球 **10+ 国家和地区、100+ 服务器节点**，灵活切换不同地区线路，随时获得更稳定、更快速的网络连接。",
        stats: [],
      },
      {
        title: "畅享全球网络服务",
        body: "稳定连接 Google、YouTube 等全球互联网服务，减少网络限制带来的不便。无论工作、学习、娱乐还是使用 AI，都能获得更顺畅的访问体验。",
        stats: [],
      },
    ],
  },
  activity: {
    kicker: "额外活动",
    loading: "加载活动中…",
    empty: "当前没有进行中的额外活动。",
    fallbackTitle: "邀请有奖",
    fallbackLead: "邀请好友，领取活动奖励。",
    progressAria: "邀请进度",
    qualified: "合格邀请",
    loginForProgress: "登录后可查看你的邀请进度。",
    perInviteKicker: "每邀奖励",
    perInviteTitle: (plan: string) => `每邀请 1 人送「${plan}」`,
    perInviteGranted: (got: number, cap: number) => `已发放 ${got} / ${cap}`,
    perInviteHint: (cap: number) => `达标前最多发放 ${cap} 次`,
    planInfoAria: "查看套餐信息",
    planInfoTitle: "套餐信息",
    planInfoEmpty: "暂无套餐详情",
    planMonths: (n: number) => `${n} 个月`,
    milestoneKicker: "达标奖励",
    milestoneTitle: (n: number, plan: string) => `满 ${n} 人送「${plan}」`,
    milestoneAuto: "达标后自动到账",
    milestoneClaim: "达标后可在本页领取",
    milestoneDone: "已领取",
    reqTitle: "怎样算合格邀请",
    reqSignup: "好友完成注册即算合格。",
    reqPaid: "好友需有实付订单",
    reqSub: "好友需已开通订阅",
    reqTraffic: "好友需下载并使用",
    reqTrafficMin: "好友需达到最低使用流量",
    shareTitle: "邀请好友",
    shareHint: "分享链接或二维码，对方注册后永久绑定。同一邀请码也计入推广佣金。",
    promoLinkKicker: "长期推广",
    promoLinkTitle: "推广中心 · 永久分佣",
    promoLinkDesc: "额外活动之外，邀请好友付费还能持续拿佣金。同一套邀请码，两份收益。",
    promoLinkCta: "去推广中心",
    copyFail: "复制失败，请手动选择文字。",
    ctaRegister: "注册去邀请",
    ctaLogin: "登录查看进度",
    summaryBoth: (per: string, n: number, plan: string) =>
      `每邀请 1 人送「${per}」，满 ${n} 人送「${plan}」`,
    summaryMilestone: (n: number, plan: string) => `满 ${n} 人送「${plan}」`,
    summaryPerInvite: (per: string) => `每邀请 1 人送「${per}」`,
  },
  about: {
    title: "关于我们",
    lead: `${site.brand} —— 安全快速的VPN 服务。`,
    whoTitle: "我们是谁",
    whoBody: `${site.brand} 面向需要稳定跨境访问的用户，提供注册、套餐领取、订阅管理与节点概览等一站式体验。`,
    offerTitle: "我们提供什么",
    offer1: "多地区节点池，可在 App 内查看状态与数量",
    offer2: "一用户多套餐：每个套餐独立订阅链接",
    offer3: "续费 / 改套餐时订阅链接保持不变",
    offer4: "兼容 Hiddify 等主流订阅客户端",
    privacyTitle: "隐私说明",
    privacyBefore: "我们仅在提供服务所必需的范围内处理账号与订阅信息。请勿将订阅链接分享给他人，以免账号被滥用。完整说明见",
    privacyLink: "隐私条款",
    privacyMid: "，使用服务前请同时阅读",
    termsLink: "用户协议",
    privacyAfter: "。",
    moreTitle: "更多",
    moreBefore: "使用问题请查看",
    guideLink: "使用教程",
    moreMid: "，或前往",
    supportLink: "联系客服",
    moreAfter: "。",
    contactTitle: "联系我们",
    tgLabel: "Telegram 客服",
    tgHint: "@titivpn_app_bot",
    tgCta: "打开",
    twitterLabel: "Twitter",
    twitterHint: "@titivpn_com",
    twitterCta: "关注",
  },
  guide: {
    title: "使用教程",
    kicker: "帮助中心",
    lead: "推荐用官方 App 一键连接；也可以把订阅导入第三方客户端。全程是：账号 → 套餐 → 连接。",
    searchPlaceholder: "搜索安装、连接、套餐等问题",
    searchAria: "搜索帮助内容",
    searchEmpty: "没有找到相关内容，请尝试其他关键词。",
    browseTitle: "浏览帮助主题",
    browseLead: "从常见任务开始，快速找到需要的说明。",
    topicStartDesc: "注册账号、领取体验套餐并开始使用",
    topicModesDesc: "使用官方 App，或导入第三方客户端",
    topicRulesDesc: "续费、设备数、订阅链接与账号安全",
    tocAria: "本页目录",
    moreTitle: "还需要帮助？",
    moreLead: "账号、支付或连接问题，可以直接联系客服。",
    tocStart: "开始使用",
    tocModes: "两种连接方式",
    tocPlatforms: "各平台要点",
    tocRules: "套餐与订阅",
    tocFaq: "常见问题",
    startTitle: "开始使用",
    start1Title: "注册账号",
    start1Before: "打开",
    start1Link: "注册页",
    start1After: `，用邮箱创建 ${site.brand} 账号。`,
    start1Trial: "限时活动期间，完成注册后系统可能自动赠送体验套餐，无需再单独领取。",
    start2Title: "开通套餐",
    start2Before: "在",
    start2Link: "套餐",
    start2After:
      "页领取免费试用，或购买付费套餐。每个套餐有独立订阅链接，可在「连接」页切换查看。",
    modesTitle: "两种连接方式",
    modesAria: "选择使用方式",
    appTab: "本站 APP",
    thirdTab: "第三方工具",
    appKicker: "推荐 · 最简单",
    appTitle: "使用本站 APP",
    appBadge: "无需导入",
    appBody: "下载安装后，用同一账号登录，套餐和线路会自动同步，不用手动复制订阅。",
    appStep1: "下载并安装本站 APP",
    appStep2: `登录 ${site.brand} 账号`,
    appStep3: "选择线路，点击连接",
    appCta: "去下载 App",
    thirdKicker: "兼容更多客户端",
    thirdTitle: "导入订阅到第三方",
    thirdBody:
      "适用于 Shadowrocket、Clash、Hiddify、Quantumult X、Surge 等支持订阅的工具。",
    thirdStep1: "打开「连接」，选好要使用的套餐",
    thirdStep2: "复制通用订阅链接，或按客户端复制专用链接；也可用二维码扫入",
    thirdStep3: "部分客户端支持一键导入 Clash / Shadowrocket",
    thirdStep4: "在客户端更新节点后，选择线路连接",
    thirdNote: "订阅链接相当于密码，请勿转发给他人。",
    thirdCta: "打开连接页",
    platformsTitle: "各平台要点",
    platIosTitle: "iOS",
    platIosBody: "优先安装官方 App，用同一账号登录即可同步套餐。也可把订阅导入 Shadowrocket 等。",
    platAndroidTitle: "Android",
    platAndroidBody: "官方 App 可走应用商店或官方 APK。没有安装包时，可用网页管理套餐并导入 Clash / Hiddify。",
    platWinTitle: "Windows",
    platWinBody: "桌面端上线后在下载页安装；此前请用网页 + Clash 等订阅客户端。",
    platMacTitle: "macOS",
    platMacBody: "桌面端上线后在下载页安装；此前请用网页 + Surge / Clash 等订阅客户端。",
    rulesTitle: "套餐与订阅规则",
    rule1: "同一套餐槽续费或改套餐时，订阅链接保持不变。",
    rule2: "在连接页「更新订阅地址」会生成新链接，旧链接立即失效，客户端需重新导入。",
    rule3: "请遵守套餐可用设备数。不要分享订阅链接，他人使用会占用你的流量，也可能导致账号被限制。",
    faqTitle: "常见问题",
    faqs: [
      {
        q: "没有官方 App 能用吗？",
        a: "可以。网页注册并开通套餐后，把订阅导入 Shadowrocket、Clash、Hiddify 等通用客户端即可。",
      },
      {
        q: "续费后链接会变吗？更新订阅地址呢？",
        a: "同一槽位续费或改套餐，链接不变。只有你主动「更新订阅地址」时才会作废旧链接。",
      },
      {
        q: "可以同时持有多个套餐吗？",
        a: "可以。每个套餐对应独立订阅链接，在「连接」页切换查看。",
      },
      {
        q: "连不上或很慢怎么办？",
        a: "先换一条线路，并到「节点」页查看地区在线状态。同时确认套餐未到期、未超出可用设备数。",
      },
      {
        q: "试用或付费开通后要等多久？",
        a: "领取或支付成功后系统会自动开通。连接页能看到套餐后即可登录 App 或导入订阅。",
      },
      {
        q: "订阅链接能分享吗？",
        a: "不要分享。别人使用你的链接会占用流量，也可能导致账号被限制。",
      },
    ],
    ctaDownload: "下载 App",
    ctaPlans: "去选套餐",
    ctaSupport: "联系客服",
  },
  download: {
    title: `下载 ${site.brand}`,
    lead: "选择你的设备平台",
    toast: (label: string) => `${label} 客户端即将上线，可先使用网页版`,
    webBefore: "也可以先",
    register: "网页注册",
    guide: "查看使用教程",
    qrAria: "手机扫码打开",
    qrTitle: "手机扫码打开",
    qrHint: "用手机浏览器扫码下载",
    noteTitle: "安装说明",
    noteIos: "iOS 通过 App Store 安装，打开后登录同一账号即可同步套餐。",
    noteAndroid: "Android 可走 Google Play 或 APK。安装来源不明的包前请确认官方地址。",
    noteDesktop: "Windows / macOS 安装包上线后可在本页下载；此前请用网页 + 通用客户端。",
  },
  support: {
    title: "联系客服",
    lead: "账号、套餐、订阅链接等问题可在这里找到我们。",
    chatTitle: "在线客服",
    chatLink: "打开聊天窗口",
    chatCta: "开始对话",
    chatHint: "网页或 App 内可直接对话，通常几分钟内回复。",
    mailTitle: "邮箱",
    mailHint: "一般会在 1–2 个工作日内回复。",
    tgTitle: "Telegram",
    tgLink: "打开客服频道 / 机器人",
    tipsTitle: "反馈时请尽量提供",
    tip1: "注册邮箱",
    tip2: "套餐名称或订阅状态截图",
    tip3: "问题发生时间与客户端名称（如 Hiddify）",
    mailCta: "发送邮件",
    mailSubject: `${site.brand} 客服咨询`,
  },
  nodes: {
    title: "节点",
    lead: "后台节点池概览：按地区查看状态与节点数量。",
    loading: "加载节点池…",
    total: "节点总数",
    regions: "覆盖地区",
    health: "在线占比",
    refresh: "刷新",
    healthTitle: "节点健康度",
    onlineOf: (active: number, total: number) => `${active}/${total} 在线`,
    updated: "更新于",
    poolTitle: "地区节点池",
    viewAria: "切换可视化",
    list: "列表",
    map: "地图",
    online: "在线",
    offline: "离线",
    other: "其他",
    statusActive: "正常",
    statusPartial: "部分可用",
    statusOffline: "离线",
    loadFailed: "加载节点失败",
    mapAria: "节点地区分布地图",
    mapHint: "虚线连回真实位置 · 点击查看",
    mapPick: "点选地图上的地区查看详情",
  },
  status: {
    title: "服务状态",
    lead: "境外机房主动探测节点协议与出口。不代表国内用户能否连上。",
    vantage: "监测点：境外机房",
    loading: "加载状态…",
    loadFailed: "加载状态失败",
    empty: "还没有探测数据。",
    total: "入站数",
    regions: "覆盖地区",
    health: "可用占比",
    refresh: "刷新",
    updated: "更新于",
    operational: "正常",
    degraded: "降级",
    outage: "故障",
    uptime: "90 天可用率",
    delay: "中位延迟",
    incidents: "近期事件",
    open: "进行中",
    resolved: "已恢复",
    none: "暂无事件",
    online: "正常",
    offline: "异常",
    statusActive: "正常",
    statusPartial: "部分可用",
    statusOffline: "离线",
    historyLegend: "近 1 小时每格 5 分钟。今日每格一小时（未到的小时为浅灰）。近 90 天每格一天。绿正常 · 黄波动 · 红故障 · 灰无数据。悬停格子可看时间。",
    historyHour: "1 小时",
    historyToday: "今日",
    history90d: "90 天",
    historyUp: "正常",
    historyPartial: "波动",
    historyDown: "故障",
    historyEmpty: "无数据",
    historyFuture: "未到",
  },
  common: {
    loading: "加载中…",
    loadFailed: "加载失败",
    email: "邮箱",
    password: "密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    code: "邮箱验证码",
    sendCode: "获取验证码",
    sending: "发送中…",
    sendFailed: "发送验证码失败",
    submit: "提交",
    cancel: "取消",
    copy: "复制",
    copied: "已复制",
    navAria: "主导航",
    unlimited: "不限",
    lifetime: "永久",
    traffic: "流量",
    days: "天",
    hours: "小时",
    claim: "领取",
    claiming: "领取中…",
    claimFailed: "领取失败",
    alreadyClaimed: "已领取",
    devCode: "开发环境验证码：",
  },
  plans: {
    title: "选择套餐",
    leadMobile: "根据您的需求，选择不同的套餐",
    leadDesktop: "开通后可在「连接」复制订阅链接",
    welcome: "注册成功。先领取免费试用，马上就能导入客户端。",
    welcomePaid: "注册成功。选择套餐开通后即可导入客户端。",
    loading: "加载套餐中…",
    empty: "暂无上架套餐",
    other: "其他",
    freeTitle: "限时免费",
    freeLead: "适合先试用，一键开通。",
    freeBadge: "免费领取",
    registerClaim: "注册领取",
    goConnect: "去连接",
    paidTitle: "选择套餐",
    paidLead: "支付成功后自动开通",
    paidEmpty: "暂无付费套餐",
    paidEmptyFree: "，可先领取上方免费试用",
    perDay: (price: string, currency: string) => `约 ${price} ${currency} / 天`,
    buyNow: "立即购买",
    renewBanner: (id: string) => `正在为 ${id} 续费时长`,
    renewEmpty: "没有与当前套餐规格相同的可续费选项，请返回新购或换一条连接。",
    inviteTitle: "邀请好友得奖励",
    inviteDesc: "分享邀请链接，好友付费你拿佣金",
    customTitle: "这些满足不了我",
    customDesc: "其他需求，联系客服定制",
    duration: "时长",
    traffic: "流量",
    devices: "设备",
    deviceUnit: "台",
    trafficUnlimited: "不限流量",
    trafficMetered: "流量套餐",
    resetDay: "天",
    resetWeek: "周",
    resetMonth: "月",
    resetYear: "年",
    resetDays: (n: number) => `${n % 1 === 0 ? n.toFixed(0) : n}天`,
    resetHours: (n: number) => `${n % 1 === 0 ? n.toFixed(0) : n}小时`,
  },
  login: {
    title: "登录",
    lead: "进入后即可查看订阅链接并导入客户端。",
    modeAria: "登录方式",
    passwordMode: "密码登录",
    codeMode: "验证码登录",
    emailRequired: "请先填写邮箱",
    codeSent: "若该邮箱已注册且已验证，验证码已发送。请查收邮件。",
    failed: "登录失败",
    passwordPh: "输入密码",
    codePh: "6 位数字",
    forgot: "忘记密码？",
    submit: "登录",
    submitting: "登录中…",
    noAccount: "还没有账号？",
    goRegister: "立即注册",
  },
  register: {
    title: "注册",
    createTitle: "创建账号",
    lead: `用邮箱创建 ${site.brand} 账号`,
    needEmailPassword: "请先填写邮箱和至少 6 位密码，再获取验证码",
    codeSent: "验证码已发送，请查收邮件（含垃圾箱）。",
    failed: "注册失败",
    passwordLabel: "密码（至少 6 位）",
    passwordPh: "设置登录密码",
    codePh: "6 位数字",
    inviteLocked: "邀请码（来自邀请链接）",
    inviteOptional: "邀请码（可选）",
    invitePh: "好友邀请码",
    submit: "注册并领取套餐",
    submitting: "创建中…",
    hasAccount: "已有账号？",
    goLogin: "去登录",
  },
  forgot: {
    title: "忘记密码",
    lead: "通过邮箱验证码设置新密码。",
    emailLabel: "注册邮箱",
    send: "发送验证码",
    sent: "若该邮箱已注册且已验证，验证码已发送。请查收邮件（含垃圾箱）。",
    sendFailed: "发送失败",
    resetFailed: "重置失败",
    backLogin: "返回登录",
    mailCode: "邮件验证码",
    newPassword: "新密码（至少 6 位）",
    newPasswordPh: "设置新密码",
    reset: "重置密码",
    submitting: "提交中…",
    resend: "重新发送验证码",
    done: "密码已重置，请使用新密码登录。",
    goLogin: "去登录",
  },
  account: {
    title: "我的",
    leadMobile: "账号、推广与帮助。",
    leadDesktop: "账号信息与常用入口，推广与帮助随时可进。",
    identityAria: "账号信息",
    uid: "用户 UID",
    loadingEmail: "加载中…",
    plans: "套餐",
    openConnect: "我的套餐",
    planCenter: "套餐中心",
    featured: "推荐",
    promoTitle: "推广中心",
    promoDesc: "邀请好友充值，可持续获得佣金，多达 3 层分成",
    activityKicker: "限时活动",
    ordersTitle: "购买记录",
    ordersDesc: "查看已成功开通的历史订单",
    logout: "退出登录",
    unverifiedTag: "未验证",
    verifiedTag: "已验证",
    verifyTitle: "验证邮箱",
    verifyLead:
      "邮箱尚未验证。若之前填错，可改成正确邮箱后再发码验证。验证后才能用邮箱在其他设备登录，也可找回密码。",
    emailInvalid: "请输入有效邮箱",
    verifyCode: "邮箱验证码",
    verifySend: "获取验证码",
    verifySubmit: "完成验证",
    verifying: "验证中…",
    verifyOk: "邮箱已验证，可在其他设备用该邮箱登录。",
    saveEmail: "仅保存新邮箱（仍未验证）",
    savingEmail: "保存中…",
    saveFailed: "保存失败",
    emailSaved: "邮箱已更新（仍未验证），可点获取验证码完成验证。",
    emailUnchanged: "邮箱未更改",
    verifyToggleHint: "点开后可修改邮箱或完成验证",
    verifyCollapse: "收起",
  },
  orders: {
    title: "购买记录",
    syncing: "同步订单中…",
    count: (n: number) => `共 ${n} 笔成功购买`,
    leadDesktop: "仅展示已开通成功的历史订单。",
    back: "← 返回我的",
    empty: "暂无成功购买记录",
    emptyHint: "购买并开通套餐后，会显示在这里",
    shop: "去选购套餐",
    fallbackTitle: "套餐订单",
    orderNo: "订单号",
    plan: "套餐",
    success: "购买成功",
    trial: "试用",
    more: "加载更多",
  },
  checkout: {
    back: "返回套餐",
    secure: "安全支付",
    title: "确认订单",
    lead: "核对套餐内容，选择支付方式后提交订单。",
    progressAria: "购买进度",
    step1: "确认订单",
    step2: "完成支付",
    step3: "自动开通",
    loading: "加载订单信息中…",
    loadFailed: "加载订单信息失败",
    createFailed: "创建支付订单失败",
    summary: "订单概要",
    amount: "订单金额",
    currency: "币种",
    method: "支付方式",
    pickChannel: "选择支付通道",
    channels: (n: number) => `共 ${n} 个可用通道`,
    instant: "即时到账",
    empty: "暂无适用于该套餐金额和币种的支付通道。",
    payAmount: "应付金额",
    submit: "提交订单并支付",
    submitting: "正在创建订单…",
    agree: "提交即表示你已确认套餐及支付信息，支付成功后系统将自动开通。",
    wechat: "微信扫码",
    alipay: "支付宝",
    crypto: "加密货币",
    online: "在线支付",
    unlimited: "不限流量",
    lifetime: "永久",
    days: (n: number) => `${n} 天`,
    devices: (n: number) => `${n} 台设备`,
    intentNew: "新购独立套餐",
    intentNewHint: "生成新的订阅链接和到期时间，不延长现有套餐。",
    intentRenew: "续费现有套餐",
    intentRenewHint: "把本次时长叠加到所选连接，订阅链接不变。",
    intentLocked: "将续费到",
    pickSlot: "选择要续费的套餐",
    slotExpired: "已过期",
    noCompatibleSlot: "没有可叠加的现有套餐，将作为新购开通。",
  },
  payment: {
    title: "支付订单",
    lead: "请在支付页面完成付款，系统会自动确认并开通套餐。",
    back: "返回套餐",
    loading: "加载订单中…",
    loadFailed: "查询订单失败",
    payAmount: "应付金额",
    scanHint: "使用微信或支付宝扫码；也可直接打开支付页面。",
    openHint: "请在第三方收银台完成加密货币支付，支付成功后本页会自动更新。",
    openPay: "打开支付页面",
    viewSub: "查看订阅连接",
    received: "已收到付款，正在自动开通，请不要重复支付。",
    provisionFail:
      "付款已确认，但自动开通暂时失败。系统会在支付平台重试通知时再次处理，请联系管理员并提供订单号。",
    reorder: "返回重新下单",
    pending: "等待支付",
    paid: "已支付，等待开通",
    provisioning: "正在开通套餐",
    provisioned: "支付成功，套餐已开通",
    failed: "订单失败",
    cancelled: "订单已取消",
    refresh: "我已支付，刷新状态",
    orderId: "订单号：",
  },
  sub: {
    title: "连接",
    lead: "切换套餐查看对应订阅信息，复制链接导入客户端。",
    claimed: "套餐已开通。可在上方切换套餐，复制对应订阅链接。",
    welcomeGranted: "注册成功。试用已开通，马上就能导入客户端。",
    granting: "正在开通试用，请稍候…",
    syncing: "同步订阅中…",
    emptyTitle: "还没有可用连接",
    emptyLead: "有可领取的免费套餐，领取后系统会自动生成订阅链接。",
    emptyLeadBuy: "暂无可领取的免费套餐，购买后即可开通连接。",
    claimCta: "领取免费套餐",
    buyCta: "去购买套餐",
    renewCta: "续费",
    myPlans: "我的套餐",
    switchAria: "切换套餐",
    syncingDot: "同步中…",
    expires: "到期",
    devices: "可用设备数",
    linkTitle: "当前套餐订阅链接",
    viewAria: "链接展示方式",
    linkTab: "链接",
    qrTab: "二维码",
    qrHint: "用客户端扫码导入订阅",
    saveQr: "保存二维码",
    qrSaved: "已保存",
    copyLink: "复制订阅链接",
    copiedPaste: "已复制，去客户端粘贴",
    copyShort: "复制",
    copiedShort: "已复制",
    copyFailed: "未复制",
    clientCopyTitle: "按客户端复制",
    manualCopyTitle: (name: string) => `${name} 链接`,
    manualCopyHint: "复制未成功，链接已选中，长按或使用系统复制即可。",
    importTitle: "一键导入客户端",
    importNeedApp: "请先安装对应应用",
    importClash: "导入 Clash",
    importClashHint: "电脑 / Android",
    importSr: "导入 Shadowrocket",
    importNote: "点击后会唤起客户端；未安装或唤起失败时，请复制上方链接手动添加订阅。",
    refresh: "更新订阅地址",
    refreshDisabledExpired: "套餐已到期，无法更新订阅地址。",
    refreshed: "已生成新链接，请重新复制并导入客户端。旧链接已失效。",
    noLink: "暂无订阅链接，可尝试更新订阅地址，或联系管理员。",
    howTitle: "如何使用",
    howLead: "新手推荐使用本站 APP，也支持常见第三方客户端。",
    howAria: "选择使用方式",
    appTab: "本站 APP",
    thirdTab: "第三方工具",
    appKicker: "推荐 · 最简单",
    appTitle: "使用本站 APP",
    appBadge: "无需导入",
    appBody: "下载并安装本站 APP，使用当前账号登录，套餐和线路会自动同步。",
    appDownload: "下载本站 APP",
    platformAria: "选择平台",
    appStep1: "下载并安装本站 APP",
    appStep2: `登录 ${site.brand} 账号`,
    appStep3: "选择线路，点击连接",
    fullGuide: "查看完整使用教程",
    thirdKicker: "兼容更多客户端",
    thirdTitle: "使用第三方工具",
    thirdBody: "适用于 Shadowrocket、Clash、Hiddify 等支持订阅链接的工具。",
    thirdStep1: "在上方选择要使用的套餐",
    thirdStep2: "复制通用订阅链接，或按客户端复制；也可用二维码扫入",
    thirdStep3: "打开工具，添加订阅并粘贴链接，或直接扫码导入",
    thirdStep4: "更新节点后选择线路连接",
    thirdNote: "订阅链接相当于密码，请勿转发给他人。",
    alsoApp: "也可下载本站 APP（更简单）",
    confirmTitle: "确认更新？",
    confirmBody: "更新地址会重新生成新的订阅链接，旧链接立即失效，客户端需重新导入。",
    confirmOk: "确认更新",
    refreshing: "更新中…",
    statusActive: "可用",
    statusExpired: "已到期",
    statusDisabled: "已停用",
    statusNone: "未开通",
    fallbackPlan: "套餐",
    fallbackSub: `${site.brand} 订阅`,
    loadFailed: "加载失败",
    syncFailed: "同步该套餐失败，显示本地缓存",
    refreshFailed: "更新订阅地址失败",
  },
  promoNav: {
    aria: "推广中心导航",
    overview: "概览",
    invite: "邀请",
    withdraw: "提现",
    redeem: "积分兑换",
  },
  promo: {
    title: "推广中心",
    loading: "加载中…",
    disabled: "推广资格已停用，请联系客服。",
    kicker: "邀请有奖",
    lead: "邀请好友，享永久绑定的分佣",
    reward: "邀请回馈",
    rewardMeta: "永久 · 按实付金额",
    tools: "推广工具",
    toolsHint: "分享即绑定",
    inviteCode: "邀请码",
    inviteLink: "邀请链接",
    copyLink: "复制邀请链接",
    copiedLink: "已复制链接",
    showQr: "查看二维码",
    qrHint: "扫码注册即永久绑定",
    qrTitle: "邀请二维码",
    qrHintLong: "扫码注册即永久绑定邀请关系",
    close: "关闭",
    balance: "可提现余额",
    yesterday: "昨日",
    pending: "待结算",
    today: "今日收益",
    total: "累计收益",
    withdrawn: "已提现",
    invitees: "邀请人数",
    goWithdraw: "去提现",
    goRedeem: "去兑换",
    commissions: "佣金明细",
    rules: "佣金规则",
    maxLevel: (n: number) => `最高 ${n} 层`,
    level: (n: number) => `${n} 层`,
    levelAria: "层级回馈比例，点击查看说明",
    levelExplain: (n: number) => `第 ${n} 层说明`,
    people: (n: number) => `当前 ${n} 人`,
    new7d: (n: number) => ` · 近 7 日新增 ${n}`,
    ruleBody:
      "好友用你的链接/邀请码注册并付费后，按上表比例结算（第 1 层为直接好友）。",
    paidBase: "按实付金额计算",
    renewBase: (rate: string) => `；续费基数 ${rate}`,
    storeFee: "；应用商店渠道先扣渠道费再算佣金",
    settle: (days: number, min: string) => `约 ${days} 天到可提现；最低提现 ${min}`,
    catalog: "佣金可兑话费或礼品卡，前往积分兑换。",
    kol: "KOL / 社媒达人可联系客服申请更高推广计划。",
    extraKicker: "额外活动",
    extraCta: "查看活动",
    extraSameLink: "同一邀请链接同时累计限时活动进度",
    tgSupport: "联系TG客服",
    contact: "联系客服",
    ban: "禁止刷单、自买自返，违者取消资格。",
    copyFail: "复制失败，请手动长按选择",
    bank: "银行卡",
    alipay: "支付宝",
    wechat: "微信",
    lv1Title: "您的直接好友",
    lv1Body: "通过您的邀请链接或邀请码注册的用户。他们付费后，按第 1 层比例给您结算佣金。",
    lv2Title: "您的间接好友",
    lv2Body: "您的直接好友再邀请来的用户。他们付费后，按第 2 层比例给您结算佣金。",
    lv3Title: "您的三层好友",
    lv3Body: "间接好友再邀请来的用户（下下级）。他们付费后，按第 3 层比例给您结算佣金。",
    lvNTitle: (n: number) => `您的 ${n} 层好友`,
    lvNBody: (n: number) =>
      `由上一层（第 ${n - 1} 层）好友邀请注册的用户。他们付费后，按第 ${n} 层比例给您结算佣金。`,
  },
  promoTeam: {
    title: "邀请与佣金",
    snapshot: "邀请速览",
    viewCommissions: "查看佣金",
    invitees: "邀请人数",
    new7d: "近 7 日新增",
    paid7d: "近 7 日充值人数",
    todayPay: "今日邀请充值",
    totalPay: "邀请累计充值",
    inviteFriends: "邀请好友",
    flow: "佣金流水",
    all: "全部",
    layer: (n: number) => `${n} 层`,
    pending: "待结算",
    settled: "已结算",
    invalid: "已失效",
    emptyInvite: "暂无邀请记录",
    emptyInviteHint: "分享邀请链接后，好友注册会出现在这里",
    emptyComm: "暂无佣金记录",
    emptyCommHint: "邀请好友充值后会在此显示",
    active: "正常",
    order: "订单",
    from: "来自",
    settleOn: (d: string) => `预计 ${d} 结算`,
  },
  promoWithdraw: {
    title: "提现",
    balance: "可提现余额",
    reviewHint: "申请后预计 T+1 工作日完成审核",
    pending: "待结算",
    withdrawn: "已提现",
    notes: "提现说明",
    min: "最低提现",
    fee: "手续费",
    reviewLi: "人工审核打款，预计 T+1 工作日处理",
    formTitle: "提交提现申请",
    formHint: "请核对收款信息",
    amount: "提现金额",
    amountPh: "例如 100",
    feePreview: (fee: string, net: string) => `预计手续费 ${fee}，到账约 ${net}`,
    method: "提现方式",
    usdt: "USDT",
    bank: "银行卡",
    usdtLabel: "USDT 地址（推荐 TRC20）",
    bankName: "开户行",
    cardNo: "卡号",
    holder: "户名",
    submit: "申请提现",
    submitting: "提交中…",
    history: "提现记录",
    empty: "暂无提现记录",
    invalidAmount: "请输入有效金额",
    needUsdt: "请填写 USDT 地址",
    needBank: "请完整填写银行卡信息",
    ok: "提现申请已提交，预计 T+1 工作日审核",
    fail: "提现失败",
    stPending: "待审核",
    stApproved: "已通过",
    stPaid: "已打款",
    stRejected: "已拒绝",
    feePaid: (fee: string, net: string) => `手续费 ${fee} · 实付 ${net}`,
  },
  promoRedeem: {
    title: "积分兑换",
    balance: "可兑换余额",
    reviewHint: "用可提现余额兑换话费或礼品卡",
    notes: "兑换说明",
    noteSpend: "提交后将冻结对应余额，审核通过后履约；拒绝则退回余额。",
    noteKinds: "目前可兑话费与礼品卡。",
    items: "兑换商品",
    itemsHint: "选择一项并填写履约信息",
    closed: "兑换暂未开放",
    emptyItems: "暂无可兑商品",
    kindPhone: "话费",
    kindGift: "礼品卡",
    filterAll: "全部",
    filterAria: "运营商分组",
    filterEmpty: "该分组暂无商品",
    carrierCmcc: "中国移动",
    carrierCucc: "中国联通",
    carrierCtcc: "中国电信",
    carrierCmccShort: "移动",
    carrierCuccShort: "联通",
    carrierCtccShort: "电信",
    phoneCarrier: (name: string) => `识别为 ${name}`,
    carrierMismatch: "所选商品与号码运营商可能不一致，请核对",
    face: "面值",
    price: "所需余额",
    stock: "库存",
    stockUnlimited: "不限",
    outOfStock: "售罄",
    phone: "充值手机号",
    phonePh: "11 位手机号",
    email: "收卡邮箱",
    emailPh: "name@example.com",
    needPhone: "请填写有效手机号",
    needEmail: "请填写有效邮箱",
    submit: "提交兑换",
    submitting: "提交中…",
    ok: "兑换申请已提交，请等待审核",
    fail: "兑换失败",
    history: "兑换记录",
    empty: "暂无兑换记录",
    stPending: "待审核",
    stFulfilled: "已履约",
    stRejected: "已拒绝",
    code: "卡密",
  },
  downloadUi: {
    ctaIos: "前往 App Store",
    ctaAndroid: "下载 Android 版",
    ctaWindows: "下载 Windows 版",
    ctaMac: "下载 macOS 版",
    hintDesktop: "桌面安装包",
    updatedAt: "更新于",
  },
  invite: {
    validLead: "好友邀请你加入。下载 App 或网页注册，即可领取套餐。",
    validLeadTrial: (plan: string) =>
      `好友邀请你加入。新用户注册即可获赠「${plan}」，下载 App 或网页注册都能开通。`,
    validLeadTrialApp: (plan: string) =>
      `好友邀请你加入。下载 App 注册即可获赠「${plan}」。`,
    invalidLead: "邀请链接无效，你仍可直接注册开始使用。",
    invalidLeadTrial: "邀请链接无效，你仍可自行注册领取体验套餐。",
    trialHint: (plan: string) => `限时活动 · 注册即送「${plan}」`,
    trialHintApp: (plan: string) => `限时活动 · App 注册即送「${plan}」`,
    codeLabel: "邀请码",
    join: `注册 ${site.brand}`,
    register: "去注册",
    login: "已有账号",
    downloadLabel: "下载 App",
    morePlatforms: "Windows / macOS 等全部平台",
    toast: (label: string) => `${label}即将上线，请先网页注册使用`,
    qrAria: "手机扫码打开",
    qrTitle: "手机扫码打开",
    qrHint: "用手机浏览器扫码",
    redirectTitle: "邀请页",
    redirectLead: "正在跳转…",
  },
  traffic: {
    label: "流量使用",
    used: (n: string) => `已用 ${n}`,
    unlimited: "不限流量",
    unlimitedBadge: "不限",
    usedPct: (n: number) => `流量已用 ${n}%`,
  },
  chat: {
    opening: "正在打开客服…",
    recalled: "已撤回",
    recalledMsg: "消息已撤回",
    placeholderMsg: "[消息]",
    copyLink: "复制链接",
    copyAll: "复制全文",
    copied: "已复制",
    loadFailed: "加载失败",
    recallFailed: "撤回失败",
    sendFailed: "发送失败",
    imageOnly: "仅支持图片文件",
    imageTooBig: "图片不能超过 4MB",
    imageSendFailed: "图片发送失败",
    aria: "在线客服",
    agent: (brand: string) => `${brand} 客服`,
    onlineLinked: "在线 · 对话已关联账号",
    onlineHint: "在线 · 通常几分钟内回复",
    close: "关闭",
    connecting: "正在连接客服…",
    welcomeTitle: "你好，需要帮忙吗？",
    welcomeBody:
      "套餐、连接、支付问题都可以问。也可直接发送截图，我们会尽快回复。",
    uploadingAlt: "上传中",
    imageAlt: "图片消息",
    uploading: "上传中",
    uploadingDot: "上传中…",
    recall: "撤回",
    sendImage: "发送图片",
    placeholder: "输入消息，Enter 发送…",
    send: "发送",
    open: "打开客服",
    fab: "客服",
    closeFab: "关闭客服",
    collapse: "收起",
  },
} as const;

const en = {
  nav: {
    home: "Home",
    plans: "Plans",
    download: "Download",
    connect: "Connect",
    account: "Account",
    userCenter: "Account center",
    menuAria: "Account menu",
    footerAria: "Footer",
    langAria: "Language",
    zh: "中文",
    en: "English",
  },
  footer: {
    nodes: "Nodes",
    about: "About",
    privacy: "Privacy",
    terms: "Terms",
  },
  help: {
    title: "Help & support",
    download: { label: "Download the app", desc: "iOS / Android / Windows / macOS" },
    guide: { label: "Setup guide", desc: "Official app, or import a third-party client" },
    support: { label: "Contact support", desc: "Account and subscription help" },
  },
  doc: {
    account: "Back to account",
    home: "Home",
  },
  home: {
    brand: site.brand,
    slogan: "Stable online, always reliable",
    leadIn: [
      "The most stable and fast VPN tool",
      `${site.brand} is both a VPN and a proxy service, ready for every environment.`,
    ],
    leadOut: "Sign up, claim a plan, copy the subscription link, and import it into a client.",
    trialChip: (plan: string) => `Limited offer · signup gift “${plan}”`,
    trialPlanFallback: "a trial plan",
    ctaConnect: "My plan",
    ctaPlans: "Pricing",
    ctaStart: "Get started",
    ctaStartTrial: "Sign up free",
    ctaLogin: "I have an account",
    downloadLabel: "Get the app",
    downloadMore: "More downloads",
    scrollHint: "Scroll down",
    stepsTitle: "Connect in three steps",
    stepsLead: "From signup to a working client in under a minute.",
    step1Title: "Create an account",
    step1Body: `Sign up for ${site.brand} with your email.`,
    step1BodyTrial: `Sign up for ${site.brand} with your email and get a trial plan automatically.`,
    step2Title: "Claim a plan",
    step2Body: "Free trials can be claimed in one tap and provision a subscription automatically.",
    step2TitleTrial: "Trial plan is granted",
    step2BodyTrial: "After signup we grant a trial plan automatically — no extra claim step.",
    step3Title: "Start using",
    step3Body: "Use the official app or third-party subscription software",
    inviteTabGift: "Invite rewards",
    inviteTabPromo: "Referral commission",
    inviteTabsAria: "Invite offers",
    inviteKicker: "Limited offer",
    inviteTitle: "Invite friends for a lifetime membership",
    inviteLead: "Each invite grants 1 day. Reach 15 invites and get a lifetime membership.",
    inviteCta: "Invite now",
    invitePerValue: "+1 day",
    invitePerLabel: "Per invite",
    inviteGoalValue: "15 invites",
    inviteGoalLabel: "Unlocks lifetime",
    promoKicker: "Ongoing referrals",
    promoTitle: "Invite friends who pay, earn forever",
    promoLead: "Earn commission on paid invites, up to 3 levels. One invite code counts for both campaign rewards and ongoing commission.",
    promoCta: "Open referral center",
    promoPerValue: "Up to 3 levels",
    promoPerLabel: "Multi-tier split",
    promoGoalValue: "Ongoing",
    promoGoalLabel: "Lifetime commission",
    featuresTitle: "Why choose us",
    features: [
      {
        title: "Bank-grade protection",
        body: "We use **AES-256 encryption** to protect your connection and data in transit. Browse the web, use AI services, or join public Wi-Fi with more peace of mind.",
        stats: [{ value: "AES-256", label: "Advanced encryption" }],
      },
      {
        title: "Fast, unblocked connections",
        body: "Optimized global routes balance speed and stability. HD video, AI services, browsing, and large file transfers stay smooth.",
        stats: [
          { value: "300 Mbps+", label: "Fast downloads" },
          { value: "12 ms", label: "Low latency" },
        ],
      },
      {
        title: "High-speed nodes worldwide",
        body: "Coverage across **10+ countries and regions, with 100+ server nodes**. Switch routes anytime for a more stable, faster connection.",
        stats: [],
      },
      {
        title: "Reach the global internet",
        body: "Stay connected to Google, YouTube, and other worldwide services with fewer network restrictions. Work, study, stream, or use AI with a smoother experience.",
        stats: [],
      },
    ],
  },
  activity: {
    kicker: "Bonus campaign",
    loading: "Loading campaign…",
    empty: "No bonus campaign is running right now.",
    fallbackTitle: "Invite rewards",
    fallbackLead: "Invite friends and claim campaign rewards.",
    progressAria: "Invite progress",
    qualified: "qualified invites",
    loginForProgress: "Sign in to see your invite progress.",
    perInviteKicker: "Per invite",
    perInviteTitle: (plan: string) => `Each invite grants “${plan}”`,
    perInviteGranted: (got: number, cap: number) => `Granted ${got} / ${cap}`,
    perInviteHint: (cap: number) => `Up to ${cap} grants before the milestone`,
    planInfoAria: "View plan details",
    planInfoTitle: "Plan details",
    planInfoEmpty: "No plan details available",
    planMonths: (n: number) => `${n} months`,
    milestoneKicker: "Milestone",
    milestoneTitle: (n: number, plan: string) => `${n} invites unlock “${plan}”`,
    milestoneAuto: "Granted automatically when you hit the goal",
    milestoneClaim: "Claim it here after you hit the goal",
    milestoneDone: "Already granted",
    reqTitle: "What counts",
    reqSignup: "A friend counts after they sign up.",
    reqPaid: "Your friend needs a paid order",
    reqSub: "Your friend needs an active subscription",
    reqTraffic: "Your friend needs to download and use the app",
    reqTrafficMin: "Your friend needs to meet the minimum data usage",
    shareTitle: "Invite friends",
    shareHint:
      "Share the link or QR code. Signup binds the invite permanently. The same code also counts toward referral commission.",
    promoLinkKicker: "Ongoing referrals",
    promoLinkTitle: "Referral center · ongoing commission",
    promoLinkDesc:
      "On top of this bonus campaign, paid invites keep earning commission. One invite code, two rewards.",
    promoLinkCta: "Open referral center",
    copyFail: "Couldn't copy. Select the text instead.",
    ctaRegister: "Sign up to invite",
    ctaLogin: "Sign in for progress",
    summaryBoth: (per: string, n: number, plan: string) =>
      `Each invite grants “${per}”. ${n} invites unlock “${plan}”.`,
    summaryMilestone: (n: number, plan: string) => `${n} invites unlock “${plan}”`,
    summaryPerInvite: (per: string) => `Each invite grants “${per}”`,
  },
  about: {
    title: "About us",
    lead: `${site.brand} — a simple, reliable personal VPN.`,
    whoTitle: "Who we are",
    whoBody: `${site.brand} helps people who need stable cross-border access: signup, plan claims, subscription management, and a node overview in one place.`,
    offerTitle: "What you get",
    offer1: "Regional node pools with status and counts in the app",
    offer2: "Multiple plans per user, each with its own subscription link",
    offer3: "The subscription URL stays the same when you renew or change a plan",
    offer4: "Works with Hiddify and other mainstream subscription clients",
    privacyTitle: "Privacy",
    privacyBefore:
      "We only process account and subscription data needed to run the service. Do not share your subscription link. See the",
    privacyLink: "Privacy Policy",
    privacyMid: " and the",
    termsLink: "Terms of Use",
    privacyAfter: " before you use the product.",
    moreTitle: "More",
    moreBefore: "For setup help, read the",
    guideLink: "guide",
    moreMid: " or",
    supportLink: "contact support",
    moreAfter: ".",
    contactTitle: "Contact",
    tgLabel: "Telegram support",
    tgHint: "@titivpn_app_bot",
    tgCta: "Open",
    twitterLabel: "Twitter",
    twitterHint: "@titivpn_com",
    twitterCta: "Follow",
  },
  guide: {
    title: "Setup guide",
    kicker: "Help center",
    lead: "The official app is the easiest way to connect. You can also import a subscription into a third-party client. Flow: account → plan → connect.",
    searchPlaceholder: "Search installation, connection, or plans",
    searchAria: "Search help",
    searchEmpty: "No matching help found. Try a different keyword.",
    browseTitle: "Browse help topics",
    browseLead: "Start with a common task and quickly find the right instructions.",
    topicStartDesc: "Create an account, activate a trial, and get started",
    topicModesDesc: "Use the official app or import a third-party client",
    topicRulesDesc: "Renewals, devices, subscription links, and account safety",
    tocAria: "On this page",
    moreTitle: "Still need help?",
    moreLead: "For account, billing, or connection issues, contact support.",
    tocStart: "Get started",
    tocModes: "Two ways to connect",
    tocPlatforms: "Platform notes",
    tocRules: "Plans and subscriptions",
    tocFaq: "FAQ",
    startTitle: "Get started",
    start1Title: "Create an account",
    start1Before: "Open the",
    start1Link: "sign-up page",
    start1After: ` and create a ${site.brand} account with your email.`,
    start1Trial:
      "During a limited offer, signup may grant a trial plan automatically — no extra claim step.",
    start2Title: "Activate a plan",
    start2Before: "On",
    start2Link: "Plans",
    start2After:
      ", claim a free trial or buy a paid plan. Each plan has its own subscription link; switch them on Connect.",
    modesTitle: "Two ways to connect",
    modesAria: "Choose how to connect",
    appTab: "Official app",
    thirdTab: "Third-party",
    appKicker: "Recommended · simplest",
    appTitle: "Use the official app",
    appBadge: "No import",
    appBody:
      "Install the app, sign in with the same account, and plans and lines sync automatically. No need to copy a subscription.",
    appStep1: "Download and install the official app",
    appStep2: `Sign in with your ${site.brand} account`,
    appStep3: "Pick a line and connect",
    appCta: "Go to downloads",
    thirdKicker: "Works with more clients",
    thirdTitle: "Import into a third-party client",
    thirdBody:
      "Works with Shadowrocket, Clash, Hiddify, Quantumult X, Surge, and other subscription clients.",
    thirdStep1: "Open Connect and select the plan you want to use",
    thirdStep2: "Copy the generic link, a client-specific link, or scan the QR code",
    thirdStep3: "Some clients support one-tap import into Clash / Shadowrocket",
    thirdStep4: "Update nodes in the client, then pick a line and connect",
    thirdNote: "A subscription link is like a password. Do not share it.",
    thirdCta: "Open Connect",
    platformsTitle: "Platform notes",
    platIosTitle: "iOS",
    platIosBody:
      "Prefer the official app and sign in with the same account. You can also import into Shadowrocket and similar apps.",
    platAndroidTitle: "Android",
    platAndroidBody:
      "Install from the store or the official APK. Until a build is available, manage plans on the web and import Clash / Hiddify.",
    platWinTitle: "Windows",
    platWinBody:
      "Install from the download page when desktop builds ship. Until then, use the web app plus Clash or another client.",
    platMacTitle: "macOS",
    platMacBody:
      "Install from the download page when desktop builds ship. Until then, use the web app plus Surge / Clash or another client.",
    rulesTitle: "Plans and subscriptions",
    rule1: "Renewing or changing the plan in the same slot keeps the subscription URL.",
    rule2:
      "“Refresh subscription URL” on Connect issues a new link and invalidates the old one immediately. Re-import it in your client.",
    rule3:
      "Stay within the device limit. Do not share the link — others will consume your traffic and may get the account limited.",
    faqTitle: "FAQ",
    faqs: [
      {
        q: "Can I use it without the official app?",
        a: "Yes. Sign up on the web, activate a plan, and import the subscription into Shadowrocket, Clash, Hiddify, or another client.",
      },
      {
        q: "Does the link change after renewal? What about refreshing the URL?",
        a: "Renewing or changing the plan in the same slot keeps the URL. Only “Refresh subscription URL” invalidates the old link.",
      },
      {
        q: "Can I hold more than one plan?",
        a: "Yes. Each plan has its own subscription link. Switch them on Connect.",
      },
      {
        q: "What if I can’t connect or it’s slow?",
        a: "Switch lines and check region status on the Nodes page. Also confirm the plan hasn’t expired and you haven’t exceeded the device limit.",
      },
      {
        q: "How long after a trial or paid checkout?",
        a: "Provisioning is automatic after a claim or successful payment. Once the plan appears on Connect, sign in to the app or import the subscription.",
      },
      {
        q: "Can I share my subscription link?",
        a: "No. Other people using your link will consume your traffic and may get the account limited.",
      },
    ],
    ctaDownload: "Download the app",
    ctaPlans: "View plans",
    ctaSupport: "Contact support",
  },
  download: {
    title: `Download ${site.brand}`,
    lead: "Pick your platform.",
    toast: (label: string) => `${label} is coming soon — use the web app for now`,
    webBefore: "Or",
    register: "sign up on the web",
    guide: "read the setup guide",
    qrAria: "Scan to open on your phone",
    qrTitle: "Scan with your phone",
    qrHint: "Open this page in your mobile browser",
    noteTitle: "Install notes",
    noteIos: "Install from the App Store, then sign in with the same account to sync plans.",
    noteAndroid: "Use Google Play or the official APK. Confirm the URL before installing sideloaded packages.",
    noteDesktop: "Windows / macOS builds will appear here. Until then, use the web app plus a generic client.",
  },
  support: {
    title: "Contact support",
    lead: "Account, plan, and subscription questions land here.",
    chatTitle: "Live chat",
    chatLink: "Open the chat",
    chatCta: "Start chat",
    chatHint: "Chat on the web or in the app. Replies usually take a few minutes.",
    mailTitle: "Email",
    mailHint: "We typically reply within 1–2 business days.",
    tgTitle: "Telegram",
    tgLink: "Open the support channel / bot",
    tipsTitle: "Please include",
    tip1: "Your signup email",
    tip2: "Plan name or a screenshot of subscription status",
    tip3: "When it happened and the client name (for example Hiddify)",
    mailCta: "Send email",
    mailSubject: `${site.brand} support`,
  },
  nodes: {
    title: "Nodes",
    lead: "Node pool overview: status and counts by region.",
    loading: "Loading node pools…",
    total: "Total nodes",
    regions: "Regions",
    health: "Online",
    refresh: "Refresh",
    healthTitle: "Pool health",
    onlineOf: (active: number, total: number) => `${active}/${total} online`,
    updated: "Updated",
    poolTitle: "Regional pools",
    viewAria: "View mode",
    list: "List",
    map: "Map",
    online: "online",
    offline: "offline",
    other: "other",
    statusActive: "OK",
    statusPartial: "Partial",
    statusOffline: "Offline",
    loadFailed: "Failed to load nodes",
    mapAria: "Node regions map",
    mapHint: "Dashed lines point to the real location · tap a region",
    mapPick: "Tap a region on the map for details",
  },
  status: {
    title: "Service status",
    lead: "Overseas probes of node protocol and egress. This is not a measure of connectivity from mainland networks.",
    vantage: "Vantage: overseas datacenter",
    loading: "Loading status…",
    loadFailed: "Failed to load status",
    empty: "No probe data yet.",
    total: "Inbounds",
    regions: "Regions",
    health: "Up",
    refresh: "Refresh",
    updated: "Updated",
    operational: "Operational",
    degraded: "Degraded",
    outage: "Outage",
    uptime: "90-day uptime",
    delay: "Median delay",
    incidents: "Recent incidents",
    open: "Ongoing",
    resolved: "Resolved",
    none: "No incidents",
    online: "up",
    offline: "down",
    statusActive: "OK",
    statusPartial: "Partial",
    statusOffline: "Offline",
    historyLegend: "Last hour: one cell per 5 minutes. Today: one cell per hour (upcoming hours are light gray). Last 90 days: one cell per day. Green up · amber degraded · red down · gray no data. Hover a cell for the time.",
    historyHour: "1h",
    historyToday: "Today",
    history90d: "90d",
    historyUp: "Up",
    historyPartial: "Degraded",
    historyDown: "Down",
    historyEmpty: "No data",
    historyFuture: "Upcoming",
  },
  common: {
    loading: "Loading…",
    loadFailed: "Failed to load",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    code: "Email code",
    sendCode: "Get code",
    sending: "Sending…",
    sendFailed: "Failed to send code",
    submit: "Submit",
    cancel: "Cancel",
    copy: "Copy",
    copied: "Copied",
    navAria: "Main navigation",
    unlimited: "Unlimited",
    lifetime: "Lifetime",
    traffic: "data",
    days: "days",
    hours: "hours",
    claim: "Claim",
    claiming: "Claiming…",
    claimFailed: "Failed to claim",
    alreadyClaimed: "Claimed",
    devCode: "Dev code: ",
  },
  plans: {
    title: "Select plan",
    leadMobile: "Choose a plan that fits your needs.",
    leadDesktop: "After activation, copy the subscription link on Connect",
    welcome: "You're in. Claim a free trial and import a client right away.",
    welcomePaid: "You're in. Choose a plan to get a subscription link.",
    loading: "Loading plans…",
    empty: "No plans available",
    other: "Other",
    freeTitle: "Limited-time free",
    freeLead: "Try first — claim in one tap.",
    freeBadge: "Free claim",
    registerClaim: "Sign up to claim",
    goConnect: "Connect",
    paidTitle: "Select plan",
    paidLead: "Activated automatically after payment",
    paidEmpty: "No paid plans",
    paidEmptyFree: " — you can claim a free trial above",
    perDay: (price: string, currency: string) => `About ${price} ${currency} / day`,
    buyNow: "Buy now",
    renewBanner: (id: string) => `Renewing duration for ${id}`,
    renewEmpty: "No compatible paid plan to renew this connection. Go back and buy a new plan instead.",
    inviteTitle: "Invite friends for rewards",
    inviteDesc: "Share your invite link and earn commission when they pay",
    customTitle: "These plans don't fit",
    customDesc: "Need something else? Contact support to customize",
    duration: "Duration",
    traffic: "Data",
    devices: "Devices",
    deviceUnit: "",
    trafficUnlimited: "Unlimited data",
    trafficMetered: "Data plan",
    resetDay: "day",
    resetWeek: "week",
    resetMonth: "month",
    resetYear: "year",
    resetDays: (n: number) => {
      const v = n % 1 === 0 ? n.toFixed(0) : String(n);
      return v === "1" ? "1 day" : `${v} days`;
    },
    resetHours: (n: number) => {
      const v = n % 1 === 0 ? n.toFixed(0) : String(n);
      return v === "1" ? "1 hour" : `${v} hours`;
    },
  },
  login: {
    title: "Log in",
    lead: "Then you can copy a subscription link and import a client.",
    modeAria: "Login method",
    passwordMode: "Password",
    codeMode: "Email code",
    emailRequired: "Enter your email first",
    codeSent: "If this email is registered and verified, a code has been sent.",
    failed: "Login failed",
    passwordPh: "Password",
    codePh: "6-digit code",
    forgot: "Forgot password?",
    submit: "Log in",
    submitting: "Signing in…",
    noAccount: "No account yet?",
    goRegister: "Sign up",
  },
  register: {
    title: "Sign up",
    createTitle: "Create account",
    lead: `Create a ${site.brand} account with your email`,
    needEmailPassword: "Enter your email and a password of at least 6 characters first",
    codeSent: "A code has been sent. Check your inbox and spam folder.",
    failed: "Sign-up failed",
    passwordLabel: "Password (min. 6 characters)",
    passwordPh: "Set a password",
    codePh: "6-digit code",
    inviteLocked: "Invite code (from your invite link)",
    inviteOptional: "Invite code (optional)",
    invitePh: "Friend's invite code",
    submit: "Sign up and claim a plan",
    submitting: "Creating…",
    hasAccount: "Already have an account?",
    goLogin: "Log in",
  },
  forgot: {
    title: "Forgot password",
    lead: "Set a new password with an email code.",
    emailLabel: "Signup email",
    send: "Send code",
    sent: "If this email is registered and verified, a code has been sent.",
    sendFailed: "Failed to send",
    resetFailed: "Reset failed",
    backLogin: "Back to login",
    mailCode: "Email code",
    newPassword: "New password (min. 6 characters)",
    newPasswordPh: "New password",
    reset: "Reset password",
    submitting: "Submitting…",
    resend: "Send another code",
    done: "Password updated. Log in with the new password.",
    goLogin: "Log in",
  },
  account: {
    title: "Account",
    leadMobile: "Account, referrals, and help.",
    leadDesktop: "Account details and shortcuts for referrals and support.",
    identityAria: "Account",
    uid: "User UID",
    loadingEmail: "Loading…",
    plans: "Plans",
    openConnect: "My plan",
    planCenter: "Plans",
    featured: "Featured",
    promoTitle: "Referral center",
    promoDesc: "Invite friends who pay and earn up to 3 levels of commission",
    activityKicker: "Limited offer",
    ordersTitle: "Purchase history",
    ordersDesc: "Successful orders that are already provisioned",
    logout: "Log out",
    unverifiedTag: "Unverified",
    verifiedTag: "Verified",
    verifyTitle: "Verify email",
    verifyLead:
      "Your email is not verified yet. If you typed it wrong, change it here, then send a code. After verification you can sign in on other devices and reset your password.",
    emailInvalid: "Enter a valid email",
    verifyCode: "Email code",
    verifySend: "Get code",
    verifySubmit: "Verify",
    verifying: "Verifying…",
    verifyOk: "Email verified. You can use it to sign in on other devices.",
    saveEmail: "Save new email (still unverified)",
    savingEmail: "Saving…",
    saveFailed: "Couldn't save",
    emailSaved: "Email updated (still unverified). Send a code to verify it.",
    emailUnchanged: "Email is unchanged",
    verifyToggleHint: "Open to change email or finish verification",
    verifyCollapse: "Close",
  },
  orders: {
    title: "Purchase history",
    syncing: "Syncing orders…",
    count: (n: number) => `${n} successful purchase${n === 1 ? "" : "s"}`,
    leadDesktop: "Only successfully provisioned orders are listed.",
    back: "← Back to account",
    empty: "No successful purchases yet",
    emptyHint: "Paid and provisioned plans will show up here",
    shop: "Browse plans",
    fallbackTitle: "Plan order",
    orderNo: "Order no.",
    plan: "Plan",
    success: "Purchased",
    trial: "trial",
    more: "Load more",
  },
  checkout: {
    back: "Back to plans",
    secure: "Secure checkout",
    title: "Confirm order",
    lead: "Review the plan, pick a payment method, then submit.",
    progressAria: "Checkout steps",
    step1: "Confirm",
    step2: "Pay",
    step3: "Activate",
    loading: "Loading order…",
    loadFailed: "Failed to load checkout",
    createFailed: "Failed to create payment",
    summary: "Order summary",
    amount: "Amount",
    currency: "Currency",
    method: "Payment",
    pickChannel: "Choose a channel",
    channels: (n: number) => `${n} available channel${n === 1 ? "" : "s"}`,
    instant: "Instant",
    empty: "No payment channel matches this plan amount and currency.",
    payAmount: "Amount due",
    submit: "Place order and pay",
    submitting: "Creating order…",
    agree: "By submitting you confirm the plan and payment details. The plan activates after payment.",
    wechat: "WeChat QR",
    alipay: "Alipay",
    crypto: "Crypto",
    online: "Online payment",
    unlimited: "Unlimited data",
    lifetime: "Lifetime",
    days: (n: number) => `${n} days`,
    devices: (n: number) => (n === 1 ? "1 device" : `${n} devices`),
    intentNew: "New independent plan",
    intentNewHint: "Creates a new subscription link and expiry. Existing plans are unchanged.",
    intentRenew: "Renew an existing plan",
    intentRenewHint: "Adds this duration to the selected connection. The link stays the same.",
    intentLocked: "Renewing",
    pickSlot: "Choose which plan to extend",
    slotExpired: "Expired",
    noCompatibleSlot: "No compatible plan to extend — this will be a new purchase.",
  },
  payment: {
    title: "Payment",
    lead: "Finish payment on the checkout page. We'll confirm and activate the plan.",
    back: "Back to plans",
    loading: "Loading order…",
    loadFailed: "Failed to load order",
    payAmount: "Amount due",
    scanHint: "Scan with WeChat or Alipay, or open the payment page.",
    openHint: "Complete crypto payment on the third-party checkout. This page updates automatically after payment.",
    openPay: "Open payment page",
    viewSub: "View subscription",
    received: "Payment received. Activating now — don't pay again.",
    provisionFail:
      "Payment is confirmed, but activation failed for now. We'll retry on the next webhook. Contact support with the order ID.",
    reorder: "Place a new order",
    pending: "Waiting for payment",
    paid: "Paid, activating",
    provisioning: "Activating plan",
    provisioned: "Paid. Plan is active",
    failed: "Order failed",
    cancelled: "Order cancelled",
    refresh: "I've paid — refresh",
    orderId: "Order ID: ",
  },
  sub: {
    title: "Connect",
    lead: "Switch plans to see each subscription and copy the link into a client.",
    claimed: "Plan is active. Switch plans above and copy the matching link.",
    welcomeGranted: "You're in. Your trial is ready — import a client now.",
    granting: "Activating your trial…",
    syncing: "Syncing subscription…",
    emptyTitle: "No connection yet",
    emptyLead: "A free plan is available — claim it to get a subscription link automatically.",
    emptyLeadBuy: "No free plan to claim. Buy a plan to get connected.",
    claimCta: "Claim free plan",
    buyCta: "Buy a plan",
    renewCta: "Renew",
    myPlans: "My plans",
    switchAria: "Switch plan",
    syncingDot: "syncing…",
    expires: "Expires",
    devices: "Devices",
    linkTitle: "Subscription link",
    viewAria: "Link view",
    linkTab: "Link",
    qrTab: "QR code",
    qrHint: "Scan with your client to import",
    saveQr: "Save QR",
    qrSaved: "Saved",
    copyLink: "Copy subscription link",
    copiedPaste: "Copied — paste it in your client",
    copyShort: "Copy",
    copiedShort: "Copied",
    copyFailed: "Not copied",
    clientCopyTitle: "Copy for your client",
    manualCopyTitle: (name: string) => `${name} link`,
    manualCopyHint: "Copy didn't go through. The link is selected — long-press or use system copy.",
    importTitle: "Import in one tap",
    importNeedApp: "Install the app first",
    importClash: "Import Clash",
    importClashHint: "Desktop / Android",
    importSr: "Import Shadowrocket",
    importNote: "This opens the client. If nothing happens, copy the link and add it manually.",
    refresh: "Rotate subscription URL",
    refreshDisabledExpired: "This plan has expired, so the URL cannot be rotated.",
    refreshed: "New link generated. Copy and import again. The old link no longer works.",
    noLink: "No subscription link yet. Try rotating the URL, or contact support.",
    howTitle: "How to connect",
    howLead: "The official app is easiest. Third-party clients work too.",
    howAria: "How to connect",
    appTab: "Official app",
    thirdTab: "Third-party",
    appKicker: "Recommended · simplest",
    appTitle: "Use the official app",
    appBadge: "No import needed",
    appBody: "Install the official app, sign in with this account, and plans sync automatically.",
    appDownload: "Download the app",
    platformAria: "Platform",
    appStep1: "Download and install the official app",
    appStep2: `Sign in with your ${site.brand} account`,
    appStep3: "Pick a line and connect",
    fullGuide: "Full setup guide",
    thirdKicker: "More clients",
    thirdTitle: "Use a third-party client",
    thirdBody: "Works with Shadowrocket, Clash, Hiddify, and other subscription clients.",
    thirdStep1: "Pick a plan above",
    thirdStep2: "Copy the generic or client-specific link, or scan the QR code",
    thirdStep3: "Open the client, add a subscription, and paste the link — or scan to import",
    thirdStep4: "Update nodes, then pick a line and connect",
    thirdNote: "Treat the subscription link like a password. Don't share it.",
    alsoApp: "Or download the official app (easier)",
    confirmTitle: "Rotate the URL?",
    confirmBody: "This generates a new subscription link. The old one stops immediately. Re-import in your client.",
    confirmOk: "Rotate",
    refreshing: "Updating…",
    statusActive: "Active",
    statusExpired: "Expired",
    statusDisabled: "Disabled",
    statusNone: "Not provisioned",
    fallbackPlan: "Plan",
    fallbackSub: `${site.brand} subscription`,
    loadFailed: "Failed to load",
    syncFailed: "Couldn't sync this plan. Showing cached data.",
    refreshFailed: "Failed to rotate the URL",
  },
  promoNav: {
    aria: "Referral navigation",
    overview: "Overview",
    invite: "Invites",
    withdraw: "Withdraw",
    redeem: "Redeem",
  },
  promo: {
    title: "Referral center",
    loading: "Loading…",
    disabled: "Referral access is disabled. Contact support.",
    kicker: "Invite rewards",
    lead: "Invite friends and earn ongoing commission",
    reward: "Invite rewards",
    rewardMeta: "Ongoing · on paid amount",
    tools: "Share tools",
    toolsHint: "Sharing binds the invite",
    inviteCode: "Invite code",
    inviteLink: "Invite link",
    copyLink: "Copy invite link",
    copiedLink: "Link copied",
    showQr: "Show QR",
    qrHint: "Scan to sign up and bind permanently",
    qrTitle: "Invite QR",
    qrHintLong: "Scanning signs up and binds the invite permanently",
    close: "Close",
    balance: "Withdrawable",
    yesterday: "Yesterday",
    pending: "Pending",
    today: "Today",
    total: "Lifetime",
    withdrawn: "Withdrawn",
    invitees: "Invitees",
    goWithdraw: "Withdraw",
    goRedeem: "Redeem",
    commissions: "Commission details",
    rules: "Commission rules",
    maxLevel: (n: number) => `Up to ${n} levels`,
    level: (n: number) => `L${n}`,
    levelAria: "Level rates — tap for details",
    levelExplain: (n: number) => `Level ${n} details`,
    people: (n: number) => `${n} people`,
    new7d: (n: number) => ` · ${n} new in 7 days`,
    ruleBody:
      "Friends who sign up with your link or code and then pay earn you the rates above (level 1 is direct).",
    paidBase: "Based on the paid amount",
    renewBase: (rate: string) => `; renewals use ${rate}`,
    storeFee: "; store channels deduct the store fee first",
    settle: (days: number, min: string) => `About ${days} days until withdrawable; minimum ${min}`,
    catalog: "Commission can be redeemed for top-ups or gift cards.",
    kol: "Creators can contact support for a higher-tier program.",
    extraKicker: "Bonus campaign",
    extraCta: "View campaign",
    extraSameLink: "The same invite link also counts toward the limited campaign",
    tgSupport: "Telegram support",
    contact: "Contact support",
    ban: "Fake orders and self-referrals are banned and will lose eligibility.",
    copyFail: "Couldn't copy. Press and hold to select.",
    bank: "Bank card",
    alipay: "Alipay",
    wechat: "WeChat",
    lv1Title: "Your direct friends",
    lv1Body: "People who signed up with your link or code. You earn level-1 commission when they pay.",
    lv2Title: "Your indirect friends",
    lv2Body: "People invited by your direct friends. You earn level-2 commission when they pay.",
    lv3Title: "Your third-level friends",
    lv3Body: "People invited by your indirect friends. You earn level-3 commission when they pay.",
    lvNTitle: (n: number) => `Your level-${n} friends`,
    lvNBody: (n: number) =>
      `People invited by the previous level (L${n - 1}). You earn level-${n} commission when they pay.`,
  },
  promoTeam: {
    title: "Invites & commissions",
    snapshot: "Invite snapshot",
    viewCommissions: "View commissions",
    invitees: "Invitees",
    new7d: "New in 7 days",
    paid7d: "Paid in 7 days",
    todayPay: "Invite payments today",
    totalPay: "Invite payments total",
    inviteFriends: "Invite friends",
    flow: "Commission ledger",
    all: "All",
    layer: (n: number) => `L${n}`,
    pending: "Pending",
    settled: "Settled",
    invalid: "Void",
    emptyInvite: "No invites yet",
    emptyInviteHint: "Shared links show up here after friends sign up",
    emptyComm: "No commissions yet",
    emptyCommHint: "They appear here after invited friends pay",
    active: "Active",
    order: "Order",
    from: "From",
    settleOn: (d: string) => `Settles ${d}`,
  },
  promoWithdraw: {
    title: "Withdraw",
    balance: "Withdrawable",
    reviewHint: "Review usually finishes in T+1 business day",
    pending: "Pending",
    withdrawn: "Withdrawn",
    notes: "Notes",
    min: "Minimum",
    fee: "Fee",
    reviewLi: "Manual payout, usually T+1 business day",
    formTitle: "Withdrawal request",
    formHint: "Double-check payout details",
    amount: "Amount",
    amountPh: "e.g. 100",
    feePreview: (fee: string, net: string) => `Est. fee ${fee}, you receive about ${net}`,
    method: "Method",
    usdt: "USDT",
    bank: "Bank card",
    usdtLabel: "USDT address (TRC20 preferred)",
    bankName: "Bank",
    cardNo: "Card number",
    holder: "Account name",
    submit: "Request withdrawal",
    submitting: "Submitting…",
    history: "History",
    empty: "No withdrawals yet",
    invalidAmount: "Enter a valid amount",
    needUsdt: "Enter a USDT address",
    needBank: "Fill in all bank details",
    ok: "Request submitted. Review usually finishes in T+1 business day.",
    fail: "Withdrawal failed",
    stPending: "Pending review",
    stApproved: "Approved",
    stPaid: "Paid",
    stRejected: "Rejected",
    feePaid: (fee: string, net: string) => `Fee ${fee} · net ${net}`,
  },
  promoRedeem: {
    title: "Redeem",
    balance: "Redeemable",
    reviewHint: "Use withdrawable balance for top-ups or gift cards",
    notes: "Notes",
    noteSpend: "Submitting holds the balance. Approved requests are fulfilled; rejected ones refund the balance.",
    noteKinds: "Top-ups and gift cards are available.",
    items: "Catalog",
    itemsHint: "Pick an item and enter fulfillment details",
    closed: "Redemption is not open yet",
    emptyItems: "No items available",
    kindPhone: "Top-up",
    kindGift: "Gift card",
    filterAll: "All",
    filterAria: "Carrier groups",
    filterEmpty: "Nothing in this group",
    carrierCmcc: "China Mobile",
    carrierCucc: "China Unicom",
    carrierCtcc: "China Telecom",
    carrierCmccShort: "Mobile",
    carrierCuccShort: "Unicom",
    carrierCtccShort: "Telecom",
    phoneCarrier: (name: string) => `Detected: ${name}`,
    carrierMismatch: "This item may not match the number’s carrier. Please check.",
    face: "Face value",
    price: "Cost",
    stock: "Stock",
    stockUnlimited: "Unlimited",
    outOfStock: "Sold out",
    phone: "Phone number",
    phonePh: "Mobile number",
    email: "Gift card email",
    emailPh: "name@example.com",
    needPhone: "Enter a valid phone number",
    needEmail: "Enter a valid email",
    submit: "Redeem",
    submitting: "Submitting…",
    ok: "Request submitted. Please wait for review.",
    fail: "Redemption failed",
    history: "History",
    empty: "No redemptions yet",
    stPending: "Pending review",
    stFulfilled: "Fulfilled",
    stRejected: "Rejected",
    code: "Code",
  },
  downloadUi: {
    ctaIos: "App Store",
    ctaAndroid: "Get Android",
    ctaWindows: "Get Windows",
    ctaMac: "Get macOS",
    hintDesktop: "Desktop installer",
    updatedAt: "Updated",
  },
  invite: {
    validLead: "A friend invited you. Download the app or sign up on the web to claim a plan.",
    validLeadTrial: (plan: string) =>
      `A friend invited you. New accounts get “${plan}” — download the app or sign up on the web.`,
    validLeadTrialApp: (plan: string) =>
      `A friend invited you. Download the app and sign up to get “${plan}”.`,
    invalidLead: "This invite link is invalid. You can still sign up and get started.",
    invalidLeadTrial: "This invite link is invalid. You can still sign up for a trial plan.",
    trialHint: (plan: string) => `Limited offer · signup gift “${plan}”`,
    trialHintApp: (plan: string) => `Limited offer · app signup gift “${plan}”`,
    codeLabel: "Invite code",
    join: `Sign up for ${site.brand}`,
    register: "Sign up",
    login: "I have an account",
    downloadLabel: "Download the app",
    morePlatforms: "Windows / macOS and all platforms",
    toast: (label: string) => `${label} is coming soon — sign up on the web first`,
    qrAria: "Scan to open on your phone",
    qrTitle: "Scan with your phone",
    qrHint: "Use your phone browser",
    redirectTitle: "Invite",
    redirectLead: "Redirecting…",
  },
  traffic: {
    label: "Data usage",
    used: (n: string) => `Used ${n}`,
    unlimited: "Unlimited data",
    unlimitedBadge: "Unlimited",
    usedPct: (n: number) => `Data used ${n}%`,
  },
  chat: {
    opening: "Opening support…",
    recalled: "Recalled",
    recalledMsg: "Message recalled",
    placeholderMsg: "[Message]",
    copyLink: "Copy link",
    copyAll: "Copy all",
    copied: "Copied",
    loadFailed: "Failed to load",
    recallFailed: "Couldn't recall",
    sendFailed: "Couldn't send",
    imageOnly: "Images only",
    imageTooBig: "Image must be under 4MB",
    imageSendFailed: "Couldn't send the image",
    aria: "Live support",
    agent: (brand: string) => `${brand} support`,
    onlineLinked: "Online · linked to your account",
    onlineHint: "Online · usually replies in a few minutes",
    close: "Close",
    connecting: "Connecting…",
    welcomeTitle: "Hi, need a hand?",
    welcomeBody:
      "Ask about plans, connections, or payments. Screenshots are welcome — we'll reply soon.",
    uploadingAlt: "Uploading",
    imageAlt: "Image",
    uploading: "Uploading",
    uploadingDot: "Uploading…",
    recall: "Recall",
    sendImage: "Send image",
    placeholder: "Type a message, Enter to send…",
    send: "Send",
    open: "Open support",
    fab: "Support",
    closeFab: "Close support",
    collapse: "Minimize",
  },
} as const;
