import { resolveSiteLocale } from "./locale";

const MAP_ZH: Record<string, string> = {
  "auth.email_taken": "该邮箱已注册，请直接登录",
  "auth.email_unverified": "邮箱尚未验证，暂不能用密码登录，请先完成邮箱验证",
  "auth.verify_code_required": "请先获取并填写邮箱验证码",
  "auth.already_registered": "当前账号已绑定邮箱，请直接登录",
  "auth.invalid_credentials": "邮箱或密码不正确",
  "auth.user_disabled": "账号已停用，请联系客服",
  "auth.verify_code_invalid": "验证码无效或已过期",
  "auth.reset_code_invalid": "验证码无效或已过期",
  "auth.code_cooldown": "验证码发送过于频繁，请稍后再试",
  "mail.ses.not_configured": "邮件服务未配置，请稍后重试或联系客服",
  "auth.anonymous_no_password": "请先绑定邮箱后再修改密码",
  "auth.password_unchanged": "新密码不能与当前密码相同",
  "plan.not_found": "套餐不存在或已下架",
  "plan.not_free_claimable": "该套餐不可免费领取",
  "subscription.plan_already_owned": "你已拥有该套餐",
  "subscription.not_found": "找不到该订阅",
  "subscription.upstream_missing": "订阅尚未绑定上游，无法更新",
  "subscription.refresh_no_url": "更新成功但未返回新链接，请稍后刷新页面",
  "user.not_found": "用户不存在",
  "user.disabled": "账号已停用",
  "invite.code_invalid": "邀请码无效或不存在，请核对；没有邀请码请留空",
  "invite.code_length_invalid": "邀请码为 3–8 位，没有请留空",
  "invite.code_format_invalid": "邀请码为 3–8 位字母或数字，没有请留空",
  "invite.inviter_disabled": "该邀请码已停用，请留空或换一个",
  "invite.self_invite": "不能填写自己的邀请码，请留空或换一个",
  "invite.already_bound": "邀请关系已绑定，无需再填邀请码",
  "invite.cross_project_forbidden": "该邀请码不属于本站，请留空或换一个",
  "invite.cycle_forbidden": "邀请关系不合法，请留空或换一个",
  "referral.disabled": "推广功能暂时关闭",
  "promo.disabled": "推广资格已停用",
  "withdraw.below_minimum": "未达到最低提现金额",
  "withdraw.insufficient_balance": "可提现余额不足",
  "withdraw.method_not_allowed": "不支持该提现方式",
  "withdraw.fee_too_high": "手续费过高，请调整金额",
  "catalog.spend_disabled": "积分兑换暂未开放",
  "catalog.not_found": "兑换商品不存在或已下架",
  "catalog.out_of_stock": "该商品已售罄",
  "spend.phone_required": "请填写有效手机号",
  "spend.email_required": "请填写有效邮箱",
  "spend.insufficient_balance": "可兑换余额不足",
  "payment.channel_unavailable": "该支付通道暂不可用",
  "payment.currency_unsupported": "该套餐币种暂不支持在线支付",
  "payment.amount_out_of_range": "套餐金额超出支付通道限额",
  "payment.provider_not_configured": "支付服务尚未完成配置",
  "payment.create_failed": "创建支付订单失败，请稍后重试",
  "payment.remote_failed": "支付平台显示订单失败",
  "payment.too_many_pending": "未支付订单过多，请先完成或等待已有订单过期后再试",
  "payment.rate_limited": "下单过于频繁，请稍后再试",
  "auth.register_rate_limited": "注册过于频繁，请稍后再试",
  "auth.register_device_limited": "该设备今日注册次数已达上限",
  "auth.register_ip_limited": "当前网络今日注册次数已达上限",
  "order.not_found": "订单不存在",
  "support.unsafe_content":
    "消息包含不安全内容（如脚本或注入代码），请删除后重发",
  "support.rate_limited": "发送过于频繁，请稍后再试",
  "support.empty_message": "消息不能为空",
  "campaign.invite_progress": "邀请人数尚未达标",
  "campaign.not_eligible": "暂时不能领取该活动",
  "campaign.not_found": "活动不存在或已结束",
  "campaign.not_active": "活动未开始或已结束",
};

const MAP_EN: Record<string, string> = {
  "auth.email_taken": "This email is already registered. Please sign in.",
  "auth.email_unverified":
    "Email not verified. Use a verification code before signing in with a password.",
  "auth.verify_code_required": "Get and enter the email verification code first",
  "auth.already_registered": "This account already has an email. Please sign in.",
  "auth.invalid_credentials": "Incorrect email or password",
  "auth.user_disabled": "Account disabled. Contact support.",
  "auth.verify_code_invalid": "Invalid or expired code",
  "auth.reset_code_invalid": "Invalid or expired code",
  "auth.code_cooldown": "Code sent too often. Try again later.",
  "mail.ses.not_configured": "Email is not configured. Try later or contact support.",
  "auth.anonymous_no_password": "Bind an email before changing the password",
  "auth.password_unchanged": "New password must be different",
  "plan.not_found": "Plan not found or unavailable",
  "plan.not_free_claimable": "This plan cannot be claimed for free",
  "subscription.plan_already_owned": "You already have this plan",
  "subscription.not_found": "Subscription not found",
  "subscription.upstream_missing": "Subscription is not bound yet and cannot be refreshed",
  "subscription.refresh_no_url":
    "Refresh succeeded but no new link was returned. Reload the page later.",
  "user.not_found": "User not found",
  "user.disabled": "Account disabled",
  "invite.code_invalid":
    "Invalid invite code. Leave it blank if you don't have one.",
  "invite.code_length_invalid": "Invite codes are 3–8 characters. Leave blank if none.",
  "invite.code_format_invalid":
    "Invite codes are 3–8 letters or numbers. Leave blank if none.",
  "invite.inviter_disabled": "This invite code is disabled. Leave blank or try another.",
  "invite.self_invite": "You can't use your own invite code.",
  "invite.already_bound": "Invite is already bound",
  "invite.cross_project_forbidden": "This invite code is not for this site.",
  "invite.cycle_forbidden": "Invalid invite relationship. Leave blank or try another.",
  "referral.disabled": "Referrals are temporarily off",
  "promo.disabled": "Referral access is disabled",
  "withdraw.below_minimum": "Below the minimum withdrawal",
  "withdraw.insufficient_balance": "Insufficient withdrawable balance",
  "withdraw.method_not_allowed": "This withdrawal method is not supported",
  "withdraw.fee_too_high": "Fee is too high. Adjust the amount.",
  "catalog.spend_disabled": "Redemption is not open yet",
  "catalog.not_found": "This item is unavailable",
  "catalog.out_of_stock": "This item is sold out",
  "spend.phone_required": "Enter a valid phone number",
  "spend.email_required": "Enter a valid email",
  "spend.insufficient_balance": "Insufficient redeemable balance",
  "payment.channel_unavailable": "This payment channel is unavailable",
  "payment.currency_unsupported": "This plan currency cannot be paid online yet",
  "payment.amount_out_of_range": "Amount is outside this channel's limits",
  "payment.provider_not_configured": "Payments are not fully configured",
  "payment.create_failed": "Couldn't create the payment. Try again later.",
  "payment.remote_failed": "The payment provider marked this order as failed",
  "payment.too_many_pending": "Too many unpaid orders. Finish or wait on an existing one first.",
  "payment.rate_limited": "Too many payment attempts. Try again shortly.",
  "auth.register_rate_limited": "Too many sign-ups. Try again later.",
  "auth.register_device_limited": "This device has reached today's sign-up limit.",
  "auth.register_ip_limited": "This network has reached today's sign-up limit.",
  "order.not_found": "Order not found",
  "support.unsafe_content":
    "Message contains unsafe content. Remove it and send again.",
  "support.rate_limited": "Sending too fast. Try again later.",
  "support.empty_message": "Message cannot be empty",
  "campaign.invite_progress": "Invite goal not reached yet",
  "campaign.not_eligible": "You can't claim this campaign right now",
  "campaign.not_found": "Campaign not found or ended",
  "campaign.not_active": "This campaign is not active",
};

export function friendlyError(err: unknown, fallback?: string) {
  const locale = resolveSiteLocale();
  const map = locale === "en" ? MAP_EN : MAP_ZH;
  const defaultFallback =
    fallback ??
    (locale === "en"
      ? "Something went wrong. Please try again."
      : "操作失败，请稍后重试");
  const raw = err instanceof Error ? err.message : String(err || "");
  return map[raw] || (raw.startsWith("http.") ? defaultFallback : raw || defaultFallback);
}
