const MAP: Record<string, string> = {
  "auth.email_taken": "该邮箱已注册，请直接登录",
  "auth.email_unverified": "邮箱尚未验证，暂不能用密码登录，请先完成邮箱验证",
  "auth.verify_code_required": "请先获取并填写邮箱验证码",
  "auth.already_registered": "当前账号已绑定邮箱，请直接登录",
  "auth.invalid_credentials": "邮箱或密码不正确",
  "auth.user_disabled": "账号已停用，请联系客服",
  "auth.verify_code_invalid": "验证码无效或已过期",
  "auth.reset_code_invalid": "验证码无效或已过期",
  "auth.code_cooldown": "验证码发送过于频繁，请稍后再试",
  "mail.ses.not_configured": "邮件服务未配置，请稍后重试或联系客服",
  "auth.anonymous_no_password": "请先绑定邮箱后再修改密码",
  "auth.password_unchanged": "新密码不能与当前密码相同",
  "plan.not_found": "套餐不存在或已下架",
  "plan.not_free_claimable": "该套餐不可免费领取",
  "subscription.plan_already_owned": "你已拥有该套餐",
  "subscription.not_found": "找不到该订阅",
  "subscription.upstream_missing": "订阅尚未绑定上游，无法更新",
  "subscription.refresh_no_url": "更新成功但未返回新链接，请稍后刷新页面",
  "user.not_found": "用户不存在",
  "user.disabled": "账号已停用",
  "invite.code_invalid": "邀请码无效或不存在，请核对；没有邀请码请留空",
  "invite.code_length_invalid": "邀请码为 3–8 位，没有请留空",
  "invite.code_format_invalid": "邀请码为 3–8 位字母或数字，没有请留空",
  "invite.inviter_disabled": "该邀请码已停用，请留空或换一个",
  "invite.self_invite": "不能填写自己的邀请码，请留空或换一个",
  "invite.already_bound": "邀请关系已绑定，无需再填邀请码",
  "invite.cross_project_forbidden": "该邀请码不属于本站，请留空或换一个",
  "invite.cycle_forbidden": "邀请关系不合法，请留空或换一个",
  "referral.disabled": "推广功能暂时关闭",
  "promo.disabled": "推广资格已停用",
  "withdraw.below_minimum": "未达到最低提现金额",
  "withdraw.insufficient_balance": "可提现余额不足",
  "withdraw.method_not_allowed": "不支持该提现方式",
  "withdraw.fee_too_high": "手续费过高，请调整金额",
  "payment.channel_unavailable": "该支付通道暂不可用",
  "payment.currency_unsupported": "该套餐币种暂不支持在线支付",
  "payment.amount_out_of_range": "套餐金额超出支付通道限额",
  "payment.provider_not_configured": "支付服务尚未完成配置",
  "payment.create_failed": "创建支付订单失败，请稍后重试",
  "payment.remote_failed": "支付平台显示订单失败",
  "order.not_found": "订单不存在",
  "support.unsafe_content":
    "消息包含不安全内容（如脚本或注入代码），请删除后重发",
  "support.rate_limited": "发送过于频繁，请稍后再试",
  "support.empty_message": "消息不能为空",
};

export function friendlyError(err: unknown, fallback = "操作失败，请稍后重试") {
  const raw = err instanceof Error ? err.message : String(err || "");
  return MAP[raw] || (raw.startsWith("http.") ? fallback : raw || fallback);
}
